from django.urls import path

from inventory import views

app_name = "inventory"

urlpatterns = [
    path(
        "management/production-lines/",
        views.ProductionLineListView.as_view(),
        name="production-line-list",
    ),
    path(
        "management/production-lines/new/",
        views.ProductionLineCreateView.as_view(),
        name="production-line-create",
    ),
    path(
        "management/production-lines/<uuid:pk>/",
        views.ProductionLineDetailView.as_view(),
        name="production-line-detail",
    ),
    path(
        "management/production-lines/<uuid:pk>/edit/",
        views.ProductionLineUpdateView.as_view(),
        name="production-line-update",
    ),
    path(
        "management/production-lines/<uuid:pk>/deactivate/",
        views.ProductionLineDeactivateView.as_view(),
        name="production-line-deactivate",
    ),
    path(
        "management/production-lines/<uuid:pk>/reactivate/",
        views.ProductionLineReactivateView.as_view(),
        name="production-line-reactivate",
    ),
    path(
        "inventory/receipts/new/",
        views.ReceiptCreateView.as_view(),
        name="receipt-create",
    ),
    path(
        "inventory/receipts/material-summary/",
        views.ReceiptMaterialSummaryView.as_view(),
        name="receipt-material-summary",
    ),
    path(
        "inventory/serialized-receipts/new/",
        views.SerializedReceiptCreateView.as_view(),
        name="serialized-receipt-create",
    ),
    path(
        "inventory/serialized-assets/<uuid:pk>/",
        views.SerializedAssetDetailView.as_view(),
        name="serialized-asset-detail",
    ),
    path(
        "inventory/serialized-assets/<uuid:pk>/issue/",
        views.SerializedIssueCreateView.as_view(),
        name="serialized-issue-create",
    ),
    path(
        "inventory/serialized-assets/<uuid:asset_pk>/returns/<uuid:issue_line_pk>/new/",
        views.SerializedReturnCreateView.as_view(),
        name="serialized-return-create",
    ),
    path(
        "inventory/serialized-assets/<uuid:pk>/transfer/",
        views.SerializedTransferCreateView.as_view(),
        name="serialized-transfer-create",
    ),
    path(
        "inventory/receipts/<uuid:pk>/",
        views.ReceiptDetailView.as_view(),
        name="receipt-detail",
    ),
    path(
        "inventory/issues/new/",
        views.IssueCreateView.as_view(),
        name="issue-create",
    ),
    path(
        "inventory/issues/<uuid:pk>/",
        views.IssueDetailView.as_view(),
        name="issue-detail",
    ),
    path(
        "inventory/returns/new/",
        views.ReturnCreateView.as_view(),
        name="return-create",
    ),
    path(
        "inventory/returns/<uuid:pk>/",
        views.ReturnDetailView.as_view(),
        name="return-detail",
    ),
    path(
        "inventory/transfers/new/",
        views.TransferCreateView.as_view(),
        name="transfer-create",
    ),
    path(
        "inventory/transfers/<uuid:pk>/",
        views.TransferDetailView.as_view(),
        name="transfer-detail",
    ),
    path(
        "inventory/stock/",
        views.StockListView.as_view(),
        name="stock-list",
    ),
    path(
        "inventory/expiry-warnings/",
        views.ExpiryWarningListView.as_view(),
        name="expiry-warning-list",
    ),
    path(
        "inventory/expiry-warnings/<uuid:pk>/inspect/",
        views.ExpiryInspectionCreateView.as_view(),
        name="expiry-inspection-create",
    ),
    path(
        "inventory/transactions/",
        views.TransactionHistoryListView.as_view(),
        name="transaction-history-list",
    ),
    path(
        "inventory/transactions/<uuid:pk>/",
        views.TransactionHistoryDetailView.as_view(),
        name="transaction-history-detail",
    ),
]
