# Generated by Django 5.2.17 on 2026-09-14 07:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


COUNTING_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION public.counting_quantity_material_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    material_tracking_mode varchar(10);
BEGIN
    SELECT material.tracking_mode
    INTO material_tracking_mode
    FROM public.catalog_material AS material
    WHERE material.id = NEW.material_id
    FOR SHARE;

    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'physical count quantity line material does not exist';
    END IF;
    IF material_tracking_mode <> 'QUANTITY' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'counting_qline_material_quantity',
            MESSAGE = 'physical count quantity line requires a QUANTITY material';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER counting_quantity_material_trg
BEFORE INSERT OR UPDATE OF material_id
ON public.counting_physicalcountquantityline
FOR EACH ROW
EXECUTE FUNCTION public.counting_quantity_material_guard();

CREATE OR REPLACE FUNCTION public.counting_material_tracking_mode_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.tracking_mode IS DISTINCT FROM OLD.tracking_mode
       AND EXISTS (
           SELECT 1
           FROM public.counting_physicalcountquantityline AS count_line
           WHERE count_line.material_id = OLD.id
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'counting_material_tracking_mode_history',
            MESSAGE = 'material tracking mode cannot change after physical count history';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER counting_material_tracking_mode_trg
BEFORE UPDATE OF tracking_mode
ON public.catalog_material
FOR EACH ROW
EXECUTE FUNCTION public.counting_material_tracking_mode_guard();

CREATE OR REPLACE FUNCTION public.counting_session_lifecycle_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status <> 'DRAFT' THEN
            RAISE EXCEPTION USING
                ERRCODE = '55000',
                CONSTRAINT = 'counting_session_started_retained',
                MESSAGE = 'started physical count session cannot be deleted';
        END IF;
        RETURN OLD;
    END IF;

    IF OLD.status = 'DRAFT' AND NEW.status = 'COMPLETED' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'counting_session_status_transition',
            MESSAGE = 'physical count session must be started before completion';
    ELSIF OLD.status = 'STARTED' AND NEW.status = 'DRAFT' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'counting_session_status_transition',
            MESSAGE = 'started physical count session cannot return to draft';
    ELSIF OLD.status = 'COMPLETED' AND NEW.status <> 'COMPLETED' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'counting_session_status_transition',
            MESSAGE = 'completed physical count session cannot be reopened';
    END IF;

    IF OLD.status IN ('STARTED', 'COMPLETED')
       AND (
           NEW.started_by_user_id IS DISTINCT FROM OLD.started_by_user_id
           OR NEW.started_at IS DISTINCT FROM OLD.started_at
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            CONSTRAINT = 'counting_session_start_immutable',
            MESSAGE = 'physical count session start metadata is immutable';
    END IF;

    IF OLD.status IN ('STARTED', 'COMPLETED')
       AND (
           NEW.scope_location_id IS DISTINCT FROM OLD.scope_location_id
           OR NEW.baseline_candidate IS DISTINCT FROM OLD.baseline_candidate
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            CONSTRAINT = 'counting_session_scope_immutable',
            MESSAGE = 'started physical count scope and baseline classification are immutable';
    END IF;

    IF OLD.status = 'COMPLETED'
       AND (
           NEW.completed_by_user_id IS DISTINCT FROM OLD.completed_by_user_id
           OR NEW.completed_at IS DISTINCT FROM OLD.completed_at
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            CONSTRAINT = 'counting_session_completion_immutable',
            MESSAGE = 'physical count session completion metadata is immutable';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER counting_session_lifecycle_update_trg
BEFORE UPDATE OF status, scope_location_id, baseline_candidate,
                 started_by_user_id, started_at, completed_by_user_id,
                 completed_at
ON public.counting_physicalcountsession
FOR EACH ROW
EXECUTE FUNCTION public.counting_session_lifecycle_guard();

CREATE TRIGGER counting_session_lifecycle_delete_trg
BEFORE DELETE
ON public.counting_physicalcountsession
FOR EACH ROW
EXECUTE FUNCTION public.counting_session_lifecycle_guard();

CREATE OR REPLACE FUNCTION public.counting_expected_snapshot_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    parent_status varchar(16);
    old_parent_status varchar(16);
BEGIN
    IF TG_OP = 'DELETE' THEN
        SELECT session.status
        INTO parent_status
        FROM public.counting_physicalcountsession AS session
        WHERE session.id = OLD.session_id
        FOR SHARE;

        IF parent_status IN ('STARTED', 'COMPLETED') THEN
            RAISE EXCEPTION USING
                ERRCODE = '55000',
                CONSTRAINT = 'counting_expected_snapshot_immutable',
                MESSAGE = 'started physical count expected snapshot is immutable';
        END IF;
        RETURN OLD;
    END IF;

    SELECT session.status
    INTO parent_status
    FROM public.counting_physicalcountsession AS session
    WHERE session.id = NEW.session_id
    FOR SHARE;

    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'physical count session does not exist';
    END IF;

    IF TG_OP = 'INSERT' THEN
        IF parent_status = 'COMPLETED'
           OR (parent_status = 'STARTED' AND NEW.expected_quantity <> 0) THEN
            RAISE EXCEPTION USING
                ERRCODE = '55000',
                CONSTRAINT = 'counting_expected_snapshot_immutable',
                MESSAGE = 'started physical count accepts only zero-expected unexpected-stock rows';
        END IF;
        RETURN NEW;
    END IF;

    SELECT session.status
    INTO old_parent_status
    FROM public.counting_physicalcountsession AS session
    WHERE session.id = OLD.session_id
    FOR SHARE;

    IF (parent_status IN ('STARTED', 'COMPLETED')
        OR old_parent_status IN ('STARTED', 'COMPLETED'))
       AND (
           NEW.session_id IS DISTINCT FROM OLD.session_id
           OR NEW.material_id IS DISTINCT FROM OLD.material_id
           OR NEW.location_id IS DISTINCT FROM OLD.location_id
           OR NEW.condition_id IS DISTINCT FROM OLD.condition_id
           OR NEW.expected_quantity IS DISTINCT FROM OLD.expected_quantity
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            CONSTRAINT = 'counting_expected_snapshot_immutable',
            MESSAGE = 'started physical count expected snapshot is immutable';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER counting_expected_snapshot_insert_trg
BEFORE INSERT
ON public.counting_physicalcountquantityline
FOR EACH ROW
EXECUTE FUNCTION public.counting_expected_snapshot_guard();

CREATE TRIGGER counting_expected_snapshot_update_trg
BEFORE UPDATE OF session_id, material_id, location_id, condition_id,
                 expected_quantity
ON public.counting_physicalcountquantityline
FOR EACH ROW
EXECUTE FUNCTION public.counting_expected_snapshot_guard();

CREATE TRIGGER counting_expected_snapshot_delete_trg
BEFORE DELETE
ON public.counting_physicalcountquantityline
FOR EACH ROW
EXECUTE FUNCTION public.counting_expected_snapshot_guard();
"""


COUNTING_GUARD_REVERSE_SQL = r"""
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.counting_physicalcountquantityline)
       OR EXISTS (SELECT 1 FROM public.counting_physicalcountsession) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'counting_reverse_requires_no_data',
            MESSAGE = 'cannot reverse physical count foundation while count data exists';
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS counting_expected_snapshot_delete_trg
    ON public.counting_physicalcountquantityline;
DROP TRIGGER IF EXISTS counting_expected_snapshot_update_trg
    ON public.counting_physicalcountquantityline;
DROP TRIGGER IF EXISTS counting_expected_snapshot_insert_trg
    ON public.counting_physicalcountquantityline;
DROP FUNCTION IF EXISTS public.counting_expected_snapshot_guard();

DROP TRIGGER IF EXISTS counting_session_lifecycle_delete_trg
    ON public.counting_physicalcountsession;
DROP TRIGGER IF EXISTS counting_session_lifecycle_update_trg
    ON public.counting_physicalcountsession;
DROP FUNCTION IF EXISTS public.counting_session_lifecycle_guard();

DROP TRIGGER IF EXISTS counting_material_tracking_mode_trg
    ON public.catalog_material;
DROP FUNCTION IF EXISTS public.counting_material_tracking_mode_guard();

DROP TRIGGER IF EXISTS counting_quantity_material_trg
    ON public.counting_physicalcountquantityline;
DROP FUNCTION IF EXISTS public.counting_quantity_material_guard();
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0004_seed_material_conditions"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysicalCountSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference_number", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Taslak"),
                            ("STARTED", "Başlatıldı"),
                            ("COMPLETED", "Tamamlandı"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Başlatılmadı"),
                            ("PENDING", "Bekliyor"),
                            ("COMPLETED", "Tamamlandı"),
                        ],
                        default="NOT_STARTED",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("baseline_candidate", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="completed_physical_count_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scope_location",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="physical_count_sessions",
                        to="locations.location",
                    ),
                ),
                (
                    "started_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="started_physical_count_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhysicalCountQuantityLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "expected_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "counted_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("counted_at", models.DateTimeField(blank=True, null=True)),
                ("approval_explanation", models.TextField(blank=True, null=True)),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("NOT_COUNTED", "Sayılmadı"),
                            ("NO_DISCREPANCY", "Fark yok"),
                            ("PENDING_APPROVAL", "Onay bekliyor"),
                            ("APPROVED", "Onaylandı"),
                            ("DISPOSITIONED", "Sonuçlandırıldı"),
                        ],
                        default="NOT_COUNTED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="approved_physical_count_quantity_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="physical_count_quantity_lines",
                        to="catalog.materialcondition",
                    ),
                ),
                (
                    "counted_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="physical_count_quantity_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="physical_count_quantity_lines",
                        to="locations.location",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="physical_count_quantity_lines",
                        to="catalog.material",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="quantity_lines",
                        to="counting.physicalcountsession",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="physicalcountsession",
            index=models.Index(
                fields=["status"], name="counting_session_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="physicalcountsession",
            index=models.Index(
                fields=["reconciliation_status"],
                name="counting_session_recon_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="physicalcountsession",
            index=models.Index(
                fields=["scope_location"], name="counting_session_scope_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="physicalcountsession",
            index=models.Index(
                fields=["started_at"], name="counting_session_started_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="physicalcountsession",
            constraint=models.UniqueConstraint(
                fields=("reference_number",),
                name="counting_session_reference_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="physicalcountsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("reference_number__regex", r"^\s*$"), _negated=True),
                name="counting_session_reference_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="physicalcountsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["DRAFT", "STARTED", "COMPLETED"])
                ),
                name="counting_session_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="physicalcountsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "reconciliation_status__in",
                        ["NOT_STARTED", "PENDING", "COMPLETED"],
                    )
                ),
                name="counting_session_recon_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="physicalcountsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("started_at__isnull", True),
                        ("started_by_user__isnull", True),
                        ("status", "DRAFT"),
                    ),
                    models.Q(
                        ("started_at__isnull", False),
                        ("started_by_user__isnull", False),
                        ("status__in", ["STARTED", "COMPLETED"]),
                    ),
                    _connector="OR",
                ),
                name="counting_session_started_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="physicalcountsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", False),
                        ("completed_by_user__isnull", False),
                        ("status", "COMPLETED"),
                    ),
                    models.Q(
                        ("completed_at__isnull", True),
                        ("completed_by_user__isnull", True),
                        ("status__in", ["DRAFT", "STARTED"]),
                    ),
                    _connector="OR",
                ),
                name="counting_session_completed_shape",
            ),
        ),
        migrations.AddIndex(
            model_name="physicalcountquantityline",
            index=models.Index(
                fields=["material"], name="counting_qline_material_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="physicalcountquantityline",
            index=models.Index(
                fields=["location"], name="counting_qline_location_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="physicalcountquantityline",
            index=models.Index(
                fields=["resolution_status"],
                name="counting_qline_resolution_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="physicalcountquantityline",
            constraint=models.UniqueConstraint(
                fields=("session", "material", "location", "condition"),
                name="counting_qline_bucket_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="physicalcountquantityline",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_quantity__gte", Decimal("0"))),
                name="counting_qline_expected_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="physicalcountquantityline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("counted_quantity__isnull", True),
                    ("counted_quantity__gte", Decimal("0")),
                    _connector="OR",
                ),
                name="counting_qline_counted_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="physicalcountquantityline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "resolution_status__in",
                        [
                            "NOT_COUNTED",
                            "NO_DISCREPANCY",
                            "PENDING_APPROVAL",
                            "APPROVED",
                            "DISPOSITIONED",
                        ],
                    )
                ),
                name="counting_qline_resolution_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="physicalcountquantityline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("counted_at__isnull", True),
                        ("counted_by_user__isnull", True),
                        ("counted_quantity__isnull", True),
                        ("resolution_status", "NOT_COUNTED"),
                    ),
                    models.Q(
                        ("counted_at__isnull", False),
                        ("counted_by_user__isnull", False),
                        ("counted_quantity__isnull", False),
                        models.Q(("resolution_status", "NOT_COUNTED"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="counting_qline_count_state_match",
            ),
        ),
        migrations.RunSQL(
            sql=COUNTING_GUARD_SQL,
            reverse_sql=COUNTING_GUARD_REVERSE_SQL,
        ),
    ]
