# Generated by Django 5.2.17 on 2026-09-14 11:58

from django.conf import settings
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def mark_existing_rows_pending(apps, schema_editor):
    PhysicalCountQuantityLine = apps.get_model(
        "counting", "PhysicalCountQuantityLine"
    )
    PhysicalCountQuantityLine.objects.filter(
        resolution_status="NOT_COUNTED",
        counted_quantity__isnull=True,
        counted_by_user__isnull=True,
        counted_at__isnull=True,
    ).update(resolution_status="PENDING_COUNT")


def restore_legacy_not_counted(apps, schema_editor):
    PhysicalCountQuantityLine = apps.get_model(
        "counting", "PhysicalCountQuantityLine"
    )
    if PhysicalCountQuantityLine.objects.filter(
        resolution_status="NOT_COUNTED"
    ).exists():
        raise IrreversibleError(
            "Cannot reverse explicit not-counted dispositions without losing actor metadata."
        )
    PhysicalCountQuantityLine.objects.filter(
        resolution_status="PENDING_COUNT"
    ).update(resolution_status="NOT_COUNTED")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_seed_material_conditions'),
        ('counting', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='physicalcountquantityline',
            name='counting_qline_resolution_valid',
        ),
        migrations.RemoveConstraint(
            model_name='physicalcountquantityline',
            name='counting_qline_count_state_match',
        ),
        migrations.AlterField(
            model_name='physicalcountquantityline',
            name='resolution_status',
            field=models.CharField(choices=[('PENDING_COUNT', 'Sayım bekliyor'), ('NOT_COUNTED', 'Sayılmadı'), ('NO_DISCREPANCY', 'Fark yok'), ('PENDING_APPROVAL', 'Onay bekliyor'), ('APPROVED', 'Onaylandı'), ('DISPOSITIONED', 'Sonuçlandırıldı')], default='PENDING_COUNT', max_length=20),
        ),
        migrations.RunPython(
            mark_existing_rows_pending,
            restore_legacy_not_counted,
        ),
        migrations.AddConstraint(
            model_name='physicalcountquantityline',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_status__in', ['PENDING_COUNT', 'NOT_COUNTED', 'NO_DISCREPANCY', 'PENDING_APPROVAL', 'APPROVED', 'DISPOSITIONED'])), name='counting_qline_resolution_valid'),
        ),
        migrations.AddConstraint(
            model_name='physicalcountquantityline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('counted_at__isnull', True), ('counted_by_user__isnull', True), ('counted_quantity__isnull', True), ('resolution_status', 'PENDING_COUNT')), models.Q(('counted_at__isnull', False), ('counted_by_user__isnull', False), ('counted_quantity__isnull', True), ('resolution_status', 'NOT_COUNTED')), models.Q(('counted_at__isnull', False), ('counted_by_user__isnull', False), ('counted_quantity__isnull', False), models.Q(('resolution_status__in', ['PENDING_COUNT', 'NOT_COUNTED']), _negated=True)), _connector='OR'), name='counting_qline_count_state_match'),
        ),
    ]
