# Generated by Django 5.2.17 on 2026-09-14 12:28

import django.db.models.deletion
import importlib
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

_foundation = importlib.import_module("counting.migrations.0001_initial")


def populate_reconciliation_status(apps, schema_editor):
    Session = apps.get_model("counting", "PhysicalCountSession")
    Line = apps.get_model("counting", "PhysicalCountQuantityLine")
    for session in Session.objects.using(schema_editor.connection.alias).filter(status="COMPLETED"):
        pending = Line.objects.using(schema_editor.connection.alias).filter(
            session_id=session.pk, resolution_status="PENDING_APPROVAL"
        ).exists()
        session.reconciliation_status = "PENDING" if (session.baseline_candidate or pending) else "COMPLETED"
        session.save(update_fields=["reconciliation_status"])


COUNT_RECONCILIATION_LINK_GUARDS_SQL = r"""
CREATE OR REPLACE FUNCTION public.counting_session_lifecycle_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status <> 'DRAFT' THEN
            RAISE EXCEPTION USING ERRCODE = '55000', CONSTRAINT = 'counting_session_started_retained', MESSAGE = 'started physical count session cannot be deleted';
        END IF;
        RETURN OLD;
    END IF;

    IF OLD.status = 'DRAFT' AND NEW.status = 'COMPLETED' THEN
        RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'counting_session_status_transition', MESSAGE = 'physical count session must be started before completion';
    ELSIF OLD.status = 'STARTED' AND NEW.status = 'DRAFT' THEN
        RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'counting_session_status_transition', MESSAGE = 'started physical count session cannot return to draft';
    ELSIF OLD.status = 'COMPLETED' AND NEW.status <> 'COMPLETED' THEN
        IF NOT (
            OLD.reconciliation_status = 'PENDING'
            AND NEW.status = 'STARTED'
            AND NEW.reconciliation_status = 'NOT_STARTED'
            AND NEW.completed_by_user_id IS NULL
            AND NEW.completed_at IS NULL
            AND EXISTS (
                SELECT 1
                FROM public.counting_physicalcountquantityrejection AS rejection
                JOIN public.counting_physicalcountquantityline AS line ON line.id = rejection.line_id
                WHERE line.session_id = OLD.id
            )
        ) THEN
            RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'counting_session_status_transition', MESSAGE = 'completed physical count session can reopen only after discrepancy rejection';
        END IF;
    END IF;

    IF OLD.status IN ('STARTED', 'COMPLETED')
       AND (NEW.started_by_user_id IS DISTINCT FROM OLD.started_by_user_id OR NEW.started_at IS DISTINCT FROM OLD.started_at) THEN
        RAISE EXCEPTION USING ERRCODE = '55000', CONSTRAINT = 'counting_session_start_immutable', MESSAGE = 'physical count session start metadata is immutable';
    END IF;
    IF OLD.status IN ('STARTED', 'COMPLETED')
       AND (NEW.scope_location_id IS DISTINCT FROM OLD.scope_location_id OR NEW.baseline_candidate IS DISTINCT FROM OLD.baseline_candidate) THEN
        RAISE EXCEPTION USING ERRCODE = '55000', CONSTRAINT = 'counting_session_scope_immutable', MESSAGE = 'started physical count scope and baseline classification are immutable';
    END IF;
    IF OLD.status = 'COMPLETED' AND NEW.status = 'COMPLETED'
       AND (NEW.completed_by_user_id IS DISTINCT FROM OLD.completed_by_user_id OR NEW.completed_at IS DISTINCT FROM OLD.completed_at) THEN
        RAISE EXCEPTION USING ERRCODE = '55000', CONSTRAINT = 'counting_session_completion_immutable', MESSAGE = 'physical count session completion metadata is immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.counting_approved_basis_immutable_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.resolution_status = 'APPROVED' AND (
        NEW.session_id IS DISTINCT FROM OLD.session_id OR
        NEW.material_id IS DISTINCT FROM OLD.material_id OR
        NEW.location_id IS DISTINCT FROM OLD.location_id OR
        NEW.condition_id IS DISTINCT FROM OLD.condition_id OR
        NEW.expected_quantity IS DISTINCT FROM OLD.expected_quantity OR
        NEW.counted_quantity IS DISTINCT FROM OLD.counted_quantity OR
        NEW.counted_by_user_id IS DISTINCT FROM OLD.counted_by_user_id OR
        NEW.counted_at IS DISTINCT FROM OLD.counted_at OR
        NEW.resolution_status IS DISTINCT FROM OLD.resolution_status OR
        NEW.approved_by_user_id IS DISTINCT FROM OLD.approved_by_user_id OR
        NEW.approved_at IS DISTINCT FROM OLD.approved_at OR
        NEW.approval_explanation IS DISTINCT FROM OLD.approval_explanation OR
        NEW.reconciliation_transaction_id IS DISTINCT FROM OLD.reconciliation_transaction_id
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '55000', CONSTRAINT = 'counting_approved_basis_immutable', MESSAGE = 'approved count reconciliation basis is immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER counting_approved_basis_immutable_trg
BEFORE UPDATE ON public.counting_physicalcountquantityline
FOR EACH ROW EXECUTE FUNCTION public.counting_approved_basis_immutable_guard();

CREATE OR REPLACE FUNCTION public.counting_rejection_immutable_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION USING ERRCODE = '55000', CONSTRAINT = 'counting_rejection_immutable', MESSAGE = 'count rejection history is immutable';
END;
$$;
CREATE TRIGGER counting_rejection_update_trg BEFORE UPDATE ON public.counting_physicalcountquantityrejection FOR EACH ROW EXECUTE FUNCTION public.counting_rejection_immutable_guard();
CREATE TRIGGER counting_rejection_delete_trg BEFORE DELETE ON public.counting_physicalcountquantityrejection FOR EACH ROW EXECUTE FUNCTION public.counting_rejection_immutable_guard();

CREATE OR REPLACE FUNCTION public.counting_result_link_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    tx_type varchar(32);
    tx_actor bigint;
    ledger_line record;
BEGIN
    IF NEW.resolution_status <> 'APPROVED' THEN RETURN NULL; END IF;
    IF char_length(btrim(NEW.approval_explanation)) NOT BETWEEN 10 AND 2000
       OR NEW.approval_explanation IS DISTINCT FROM btrim(NEW.approval_explanation) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'counting_approval_explanation_valid', MESSAGE = 'approval explanation must be trimmed and contain 10 to 2000 characters';
    END IF;
    SELECT transaction_type, acting_user_id INTO tx_type, tx_actor
    FROM public.inventory_inventorytransaction WHERE id = NEW.reconciliation_transaction_id;
    IF tx_type IS DISTINCT FROM 'COUNT_RECONCILIATION' OR tx_actor IS DISTINCT FROM NEW.approved_by_user_id THEN
        RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'counting_result_transaction_match', MESSAGE = 'approved count result must be an actor-matched COUNT_RECONCILIATION';
    END IF;
    SELECT * INTO ledger_line FROM public.inventory_inventorytransactionline
    WHERE transaction_id = NEW.reconciliation_transaction_id;
    IF NOT FOUND OR (SELECT count(*) FROM public.inventory_inventorytransactionline WHERE transaction_id = NEW.reconciliation_transaction_id) <> 1
       OR ledger_line.material_id IS DISTINCT FROM NEW.material_id
       OR ledger_line.condition_id IS DISTINCT FROM NEW.condition_id
       OR COALESCE(ledger_line.source_location_id, ledger_line.target_location_id) IS DISTINCT FROM NEW.location_id
       OR ledger_line.quantity IS DISTINCT FROM abs(NEW.counted_quantity - NEW.expected_quantity)
       OR (NEW.counted_quantity > NEW.expected_quantity AND (ledger_line.source_location_id IS NOT NULL OR ledger_line.target_location_id IS NULL))
       OR (NEW.counted_quantity < NEW.expected_quantity AND (ledger_line.source_location_id IS NULL OR ledger_line.target_location_id IS NOT NULL)) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'counting_result_line_match', MESSAGE = 'COUNT_RECONCILIATION line must match its approved count basis';
    END IF;
    RETURN NULL;
END;
$$;
CREATE CONSTRAINT TRIGGER counting_result_link_trg
AFTER INSERT OR UPDATE ON public.counting_physicalcountquantityline
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.counting_result_link_guard();

CREATE OR REPLACE FUNCTION public.counting_result_required_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.transaction_type = 'COUNT_RECONCILIATION' AND (
        SELECT count(*) FROM public.counting_physicalcountquantityline
        WHERE reconciliation_transaction_id = NEW.id AND resolution_status = 'APPROVED'
    ) <> 1 THEN
        RAISE EXCEPTION USING ERRCODE = '23514', CONSTRAINT = 'counting_result_link_required', MESSAGE = 'COUNT_RECONCILIATION requires exactly one approved count owner';
    END IF;
    RETURN NULL;
END;
$$;
CREATE CONSTRAINT TRIGGER counting_result_required_trg
AFTER INSERT OR UPDATE ON public.inventory_inventorytransaction
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.counting_result_required_guard();
"""

REVERSE_LINK_GUARDS_SQL = r"""
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.counting_physicalcountquantityrejection)
       OR EXISTS (
            SELECT 1
            FROM public.counting_physicalcountquantityline
            WHERE resolution_status = 'APPROVED'
               OR reconciliation_transaction_id IS NOT NULL
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'counting_reconciliation_reverse_requires_no_data',
            MESSAGE = 'cannot reverse count reconciliation while approval/rejection history exists';
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS counting_result_required_trg ON public.inventory_inventorytransaction;
DROP FUNCTION IF EXISTS public.counting_result_required_guard();
DROP TRIGGER IF EXISTS counting_result_link_trg ON public.counting_physicalcountquantityline;
DROP FUNCTION IF EXISTS public.counting_result_link_guard();
DROP TRIGGER IF EXISTS counting_rejection_delete_trg ON public.counting_physicalcountquantityrejection;
DROP TRIGGER IF EXISTS counting_rejection_update_trg ON public.counting_physicalcountquantityrejection;
DROP FUNCTION IF EXISTS public.counting_rejection_immutable_guard();
DROP TRIGGER IF EXISTS counting_approved_basis_immutable_trg ON public.counting_physicalcountquantityline;
DROP FUNCTION IF EXISTS public.counting_approved_basis_immutable_guard();
""" + _foundation.COUNTING_GUARD_SQL[
    _foundation.COUNTING_GUARD_SQL.index(
        "CREATE OR REPLACE FUNCTION public.counting_session_lifecycle_guard()"
    ):
    _foundation.COUNTING_GUARD_SQL.index(
        "CREATE TRIGGER counting_session_lifecycle_update_trg"
    )
]


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_seed_material_conditions'),
        ('counting', '0002_explicit_not_counted_disposition'),
        ('inventory', '0010_count_reconciliation_kernel'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalCountQuantityRejection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rejected_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('counted_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('counted_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='physicalcountquantityline',
            options={'permissions': [('decide_discrepancy', 'Can approve or reject count discrepancy')]},
        ),
        migrations.AddField(
            model_name='physicalcountquantityline',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalcountquantityline',
            name='reconciliation_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='physical_count_quantity_result', to='inventory.inventorytransaction'),
        ),
        migrations.AddConstraint(
            model_name='physicalcountquantityline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approval_explanation__isnull', False), ('approved_at__isnull', False), ('approved_by_user__isnull', False), ('reconciliation_transaction__isnull', False), ('resolution_status', 'APPROVED')), models.Q(models.Q(('resolution_status', 'APPROVED'), _negated=True), ('approval_explanation__isnull', True), ('approved_at__isnull', True), ('approved_by_user__isnull', True), ('reconciliation_transaction__isnull', True)), _connector='OR'), name='counting_qline_approval_shape'),
        ),
        migrations.AddConstraint(
            model_name='physicalcountquantityline',
            constraint=models.CheckConstraint(
                condition=~models.Q(
                    approved_by_user=models.F('counted_by_user'),
                    resolution_status='APPROVED',
                ),
                name='counting_qline_no_self_approval',
            ),
        ),
        migrations.RunPython(populate_reconciliation_status, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='physicalcountsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reconciliation_status', 'NOT_STARTED'), ('status__in', ['DRAFT', 'STARTED'])), models.Q(('reconciliation_status__in', ['PENDING', 'COMPLETED']), ('status', 'COMPLETED')), _connector='OR'), name='counting_session_recon_status_match'),
        ),
        migrations.AddField(
            model_name='physicalcountquantityrejection',
            name='counted_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rejected_count_quantity_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='physicalcountquantityrejection',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rejections', to='counting.physicalcountquantityline'),
        ),
        migrations.AddField(
            model_name='physicalcountquantityrejection',
            name='rejected_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rejected_physical_count_quantity_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='physicalcountquantityrejection',
            constraint=models.CheckConstraint(condition=models.Q(('counted_quantity__gte', Decimal('0'))), name='counting_qreject_counted_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='physicalcountquantityrejection',
            constraint=models.CheckConstraint(condition=models.Q(('reason__isnull', True), models.Q(('reason__regex', '^\\s*$'), _negated=True), _connector='OR'), name='counting_qreject_reason_nonblank'),
        ),
        migrations.RunSQL(
            sql=COUNT_RECONCILIATION_LINK_GUARDS_SQL,
            reverse_sql=REVERSE_LINK_GUARDS_SQL,
        ),
    ]
