# Generated by Django 5.2.17 on 2026-09-14 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


COUNTING_SERIALIZED_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION public.counting_serialized_material_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    material_tracking_mode varchar(10);
    asset_material_id uuid;
    asset_internal_code varchar(64);
    asset_serial_number varchar(255);
BEGIN
    SELECT material.tracking_mode
    INTO material_tracking_mode
    FROM public.catalog_material AS material
    WHERE material.id = NEW.material_id
    FOR SHARE;

    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'physical count serialized line material does not exist';
    END IF;
    IF material_tracking_mode <> 'SERIALIZED' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'counting_sline_material_serialized',
            MESSAGE = 'physical count serialized line requires a SERIALIZED material';
    END IF;

    IF NEW.serialized_asset_id IS NOT NULL THEN
        SELECT asset.material_id, asset.internal_asset_code, asset.serial_number
        INTO asset_material_id, asset_internal_code, asset_serial_number
        FROM public.inventory_serializedasset AS asset
        WHERE asset.id = NEW.serialized_asset_id
        FOR SHARE;

        IF NOT FOUND THEN
            RAISE EXCEPTION USING
                ERRCODE = '23503',
                MESSAGE = 'physical count serialized line asset does not exist';
        END IF;
        IF asset_material_id IS DISTINCT FROM NEW.material_id
           OR asset_internal_code IS DISTINCT FROM NEW.internal_asset_code
           OR asset_serial_number IS DISTINCT FROM NEW.serial_number THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'counting_sline_asset_identity_match',
                MESSAGE = 'serialized count line identity must match the linked asset';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER counting_serialized_material_trg
BEFORE INSERT OR UPDATE OF material_id, serialized_asset_id,
                           internal_asset_code, serial_number
ON public.counting_physicalcountserializedline
FOR EACH ROW
EXECUTE FUNCTION public.counting_serialized_material_guard();

CREATE OR REPLACE FUNCTION public.counting_material_tracking_mode_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.tracking_mode IS DISTINCT FROM OLD.tracking_mode
       AND (
           EXISTS (
               SELECT 1
               FROM public.counting_physicalcountquantityline AS count_line
               WHERE count_line.material_id = OLD.id
           )
           OR EXISTS (
               SELECT 1
               FROM public.counting_physicalcountserializedline AS count_line
               WHERE count_line.material_id = OLD.id
           )
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'counting_material_tracking_mode_history',
            MESSAGE = 'material tracking mode cannot change after physical count history';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.counting_serialized_snapshot_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    parent_status varchar(16);
    old_parent_status varchar(16);
BEGIN
    IF TG_OP = 'DELETE' THEN
        SELECT session.status
        INTO parent_status
        FROM public.counting_physicalcountsession AS session
        WHERE session.id = OLD.session_id
        FOR SHARE;

        IF parent_status IN ('STARTED', 'COMPLETED') THEN
            RAISE EXCEPTION USING
                ERRCODE = '55000',
                CONSTRAINT = 'counting_serialized_snapshot_immutable',
                MESSAGE = 'started serialized count snapshot is immutable';
        END IF;
        RETURN OLD;
    END IF;

    SELECT session.status
    INTO parent_status
    FROM public.counting_physicalcountsession AS session
    WHERE session.id = NEW.session_id
    FOR SHARE;

    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'physical count session does not exist';
    END IF;

    IF TG_OP = 'INSERT' THEN
        IF parent_status = 'COMPLETED' THEN
            RAISE EXCEPTION USING
                ERRCODE = '55000',
                CONSTRAINT = 'counting_serialized_snapshot_immutable',
                MESSAGE = 'completed serialized count accepts no new rows';
        ELSIF parent_status = 'STARTED'
              AND NOT (
                  NEW.expected_present = false
                  AND NEW.observed_present = true
              ) THEN
            RAISE EXCEPTION USING
                ERRCODE = '55000',
                CONSTRAINT = 'counting_serialized_snapshot_immutable',
                MESSAGE = 'started serialized count accepts only unexpected observed-present rows';
        ELSIF parent_status = 'DRAFT'
              AND NOT (
                  NEW.expected_present = true
                  AND NEW.resolution_status = 'PENDING_COUNT'
                  AND NEW.observed_present IS NULL
              ) THEN
            RAISE EXCEPTION USING
                ERRCODE = '55000',
                CONSTRAINT = 'counting_serialized_snapshot_immutable',
                MESSAGE = 'draft serialized count accepts only expected snapshot rows';
        END IF;
        RETURN NEW;
    END IF;

    SELECT session.status
    INTO old_parent_status
    FROM public.counting_physicalcountsession AS session
    WHERE session.id = OLD.session_id
    FOR SHARE;

    IF (parent_status IN ('STARTED', 'COMPLETED')
        OR old_parent_status IN ('STARTED', 'COMPLETED'))
       AND (
           NEW.session_id IS DISTINCT FROM OLD.session_id
           OR NEW.serialized_asset_id IS DISTINCT FROM OLD.serialized_asset_id
           OR NEW.material_id IS DISTINCT FROM OLD.material_id
           OR NEW.internal_asset_code IS DISTINCT FROM OLD.internal_asset_code
           OR NEW.serial_number IS DISTINCT FROM OLD.serial_number
           OR NEW.expected_present IS DISTINCT FROM OLD.expected_present
           OR NEW.expected_location_id IS DISTINCT FROM OLD.expected_location_id
           OR NEW.expected_condition_id IS DISTINCT FROM OLD.expected_condition_id
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            CONSTRAINT = 'counting_serialized_snapshot_immutable',
            MESSAGE = 'started serialized count snapshot is immutable';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER counting_serialized_snapshot_insert_trg
BEFORE INSERT
ON public.counting_physicalcountserializedline
FOR EACH ROW
EXECUTE FUNCTION public.counting_serialized_snapshot_guard();

CREATE TRIGGER counting_serialized_snapshot_update_trg
BEFORE UPDATE OF session_id, serialized_asset_id, material_id,
                 internal_asset_code, serial_number, expected_present,
                 expected_location_id, expected_condition_id
ON public.counting_physicalcountserializedline
FOR EACH ROW
EXECUTE FUNCTION public.counting_serialized_snapshot_guard();

CREATE TRIGGER counting_serialized_snapshot_delete_trg
BEFORE DELETE
ON public.counting_physicalcountserializedline
FOR EACH ROW
EXECUTE FUNCTION public.counting_serialized_snapshot_guard();

CREATE OR REPLACE FUNCTION public.counting_serialized_completed_history_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    parent_status varchar(16);
BEGIN
    SELECT session.status
    INTO parent_status
    FROM public.counting_physicalcountsession AS session
    WHERE session.id = NEW.session_id
    FOR SHARE;

    IF parent_status = 'COMPLETED'
       AND (
           NEW.observed_present IS DISTINCT FROM OLD.observed_present
           OR NEW.observed_location_id IS DISTINCT FROM OLD.observed_location_id
           OR NEW.observed_condition_id IS DISTINCT FROM OLD.observed_condition_id
           OR NEW.counted_by_user_id IS DISTINCT FROM OLD.counted_by_user_id
           OR NEW.counted_at IS DISTINCT FROM OLD.counted_at
           OR NEW.resolution_status IS DISTINCT FROM OLD.resolution_status
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            CONSTRAINT = 'counting_serialized_completed_immutable',
            MESSAGE = 'completed serialized count history is immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER counting_serialized_completed_history_trg
BEFORE UPDATE OF observed_present, observed_location_id, observed_condition_id,
                 counted_by_user_id, counted_at, resolution_status
ON public.counting_physicalcountserializedline
FOR EACH ROW
EXECUTE FUNCTION public.counting_serialized_completed_history_guard();
"""


COUNTING_SERIALIZED_GUARD_REVERSE_SQL = r"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM public.counting_physicalcountserializedline
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'counting_serialized_reverse_requires_no_data',
            MESSAGE = 'cannot reverse serialized physical count while serialized count history exists';
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS counting_serialized_completed_history_trg
    ON public.counting_physicalcountserializedline;
DROP FUNCTION IF EXISTS public.counting_serialized_completed_history_guard();

DROP TRIGGER IF EXISTS counting_serialized_snapshot_delete_trg
    ON public.counting_physicalcountserializedline;
DROP TRIGGER IF EXISTS counting_serialized_snapshot_update_trg
    ON public.counting_physicalcountserializedline;
DROP TRIGGER IF EXISTS counting_serialized_snapshot_insert_trg
    ON public.counting_physicalcountserializedline;
DROP FUNCTION IF EXISTS public.counting_serialized_snapshot_guard();

DROP TRIGGER IF EXISTS counting_serialized_material_trg
    ON public.counting_physicalcountserializedline;
DROP FUNCTION IF EXISTS public.counting_serialized_material_guard();

CREATE OR REPLACE FUNCTION public.counting_material_tracking_mode_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.tracking_mode IS DISTINCT FROM OLD.tracking_mode
       AND EXISTS (
           SELECT 1
           FROM public.counting_physicalcountquantityline AS count_line
           WHERE count_line.material_id = OLD.id
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'counting_material_tracking_mode_history',
            MESSAGE = 'material tracking mode cannot change after physical count history';
    END IF;
    RETURN NEW;
END;
$$;
"""


class Migration(migrations.Migration):


    dependencies = [
        ('catalog', '0004_seed_material_conditions'),
        ('counting', '0003_physicalcountquantityrejection_and_more'),
        ('inventory', '0010_count_reconciliation_kernel'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalCountSerializedLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_asset_code', models.CharField(max_length=64)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_present', models.BooleanField()),
                ('observed_present', models.BooleanField(blank=True, null=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_status', models.CharField(choices=[('PENDING_COUNT', 'Sayım bekliyor'), ('NOT_COUNTED', 'Sayılmadı'), ('NO_DISCREPANCY', 'Fark yok'), ('PENDING_APPROVAL', 'Onay bekliyor')], default='PENDING_COUNT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counted_by_user', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='physical_count_serialized_lines', to=settings.AUTH_USER_MODEL)),
                ('expected_condition', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='expected_physical_count_serialized_lines', to='catalog.materialcondition')),
                ('expected_location', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='expected_physical_count_serialized_lines', to='locations.location')),
                ('material', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='physical_count_serialized_lines', to='catalog.material')),
                ('observed_condition', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='observed_physical_count_serialized_lines', to='catalog.materialcondition')),
                ('observed_location', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='observed_physical_count_serialized_lines', to='locations.location')),
                ('serialized_asset', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='physical_count_serialized_lines', to='inventory.serializedasset')),
                ('session', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='serialized_lines', to='counting.physicalcountsession')),
            ],
            options={
                'indexes': [models.Index(fields=['material'], name='counting_sline_material_idx'), models.Index(fields=['serialized_asset'], name='counting_sline_asset_idx'), models.Index(fields=['resolution_status'], name='counting_sline_resolution_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'internal_asset_code'), name='counting_sline_session_code_uniq'), models.UniqueConstraint(condition=models.Q(('serialized_asset__isnull', False)), fields=('session', 'serialized_asset'), name='counting_sline_session_asset_uniq'), models.UniqueConstraint(condition=models.Q(('serial_number__isnull', False)), fields=('session', 'material', 'serial_number'), name='counting_sline_session_serial_uniq'), models.CheckConstraint(condition=models.Q(('internal_asset_code__regex', '^\\s*$'), _negated=True), name='counting_sline_code_nonblank'), models.CheckConstraint(condition=models.Q(('serial_number__isnull', True), models.Q(('serial_number__regex', '^\\s*$'), _negated=True), _connector='OR'), name='counting_sline_serial_null_or_nonblank'), models.CheckConstraint(condition=models.Q(('resolution_status__in', ['PENDING_COUNT', 'NOT_COUNTED', 'NO_DISCREPANCY', 'PENDING_APPROVAL'])), name='counting_sline_resolution_valid'), models.CheckConstraint(condition=models.Q(models.Q(('expected_condition__isnull', False), ('expected_location__isnull', False), ('expected_present', True), ('serialized_asset__isnull', False)), models.Q(('expected_condition__isnull', True), ('expected_location__isnull', True), ('expected_present', False)), _connector='OR'), name='counting_sline_expected_shape'), models.CheckConstraint(condition=models.Q(models.Q(('counted_at__isnull', True), ('counted_by_user__isnull', True), ('expected_condition__isnull', False), ('expected_location__isnull', False), ('expected_present', True), ('observed_condition__isnull', True), ('observed_location__isnull', True), ('observed_present__isnull', True), ('resolution_status', 'PENDING_COUNT'), ('serialized_asset__isnull', False)), models.Q(('counted_at__isnull', False), ('counted_by_user__isnull', False), ('expected_condition__isnull', False), ('expected_location__isnull', False), ('expected_present', True), ('observed_condition__isnull', True), ('observed_location__isnull', True), ('observed_present__isnull', True), ('resolution_status', 'NOT_COUNTED'), ('serialized_asset__isnull', False)), models.Q(('counted_at__isnull', False), ('counted_by_user__isnull', False), ('expected_condition__isnull', False), ('expected_location__isnull', False), ('expected_present', True), ('observed_condition__isnull', True), ('observed_location__isnull', True), ('observed_present', False), ('resolution_status', 'PENDING_APPROVAL'), ('serialized_asset__isnull', False)), models.Q(('counted_at__isnull', False), ('counted_by_user__isnull', False), ('expected_condition__isnull', False), ('expected_location__isnull', False), ('expected_present', True), ('observed_condition', models.F('expected_condition')), ('observed_location', models.F('expected_location')), ('observed_present', True), ('resolution_status', 'NO_DISCREPANCY'), ('serialized_asset__isnull', False)), models.Q(('counted_at__isnull', False), ('counted_by_user__isnull', False), ('expected_condition__isnull', False), ('expected_location__isnull', False), ('expected_present', True), ('observed_condition__isnull', False), ('observed_location__isnull', False), ('observed_present', True), ('resolution_status', 'PENDING_APPROVAL'), ('serialized_asset__isnull', False), models.Q(('observed_condition', models.F('expected_condition')), ('observed_location', models.F('expected_location')), _negated=True)), models.Q(('counted_at__isnull', False), ('counted_by_user__isnull', False), ('expected_condition__isnull', True), ('expected_location__isnull', True), ('expected_present', False), ('observed_condition__isnull', False), ('observed_location__isnull', False), ('observed_present', True), ('resolution_status', 'PENDING_APPROVAL')), _connector='OR'), name='counting_sline_state_shape')],
            },
        ),
        migrations.RunSQL(
            sql=COUNTING_SERIALIZED_GUARD_SQL,
            reverse_sql=COUNTING_SERIALIZED_GUARD_REVERSE_SQL,
        ),
    ]
