# Generated by Django 5.2.17 on 2026-09-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_access', 'Rol ve kullanıcı erişimlerini yönetebilir')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
