# Generated by Django 5.2.17 on 2026-09-11 20:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('employee_number',), name='accounts_employee_number_uniq'),
                    models.CheckConstraint(condition=models.Q(('employee_number__regex', '^\\s*$'), _negated=True), name='accounts_employee_number_nonblank'),
                    models.CheckConstraint(condition=models.Q(('first_name__regex', '^\\s*$'), _negated=True), name='accounts_employee_first_name_nonblank'),
                    models.CheckConstraint(condition=models.Q(('last_name__regex', '^\\s*$'), _negated=True), name='accounts_employee_last_name_nonblank'),
                ],
            },
        ),
    ]
