# Generated by Django 5.2.17 on 2026-09-12 06:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


KERNEL_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION public.inventory_ledger_immutability_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION USING
        ERRCODE = '55000',
        MESSAGE = TG_TABLE_NAME || ' rows are immutable';
END;
$$;

CREATE TRIGGER inventory_tx_immutable_trg
BEFORE UPDATE OR DELETE ON public.inventory_inventorytransaction
FOR EACH ROW
EXECUTE FUNCTION public.inventory_ledger_immutability_guard();

CREATE TRIGGER inventory_line_immutable_trg
BEFORE UPDATE OR DELETE ON public.inventory_inventorytransactionline
FOR EACH ROW
EXECUTE FUNCTION public.inventory_ledger_immutability_guard();

CREATE OR REPLACE FUNCTION public.inventory_tx_requires_line_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM public.inventory_inventorytransactionline AS line
        WHERE line.transaction_id = NEW.id
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_tx_requires_line',
            MESSAGE = 'inventory transaction must contain at least one line';
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER inventory_tx_requires_line_trg
AFTER INSERT ON public.inventory_inventorytransaction
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION public.inventory_tx_requires_line_guard();

CREATE OR REPLACE FUNCTION public.inventory_line_quantity_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    material_tracking_mode varchar(10);
    material_unit_id uuid;
BEGIN
    SELECT material.tracking_mode, material.unit_id
    INTO material_tracking_mode, material_unit_id
    FROM public.catalog_material AS material
    WHERE material.id = NEW.material_id
    FOR SHARE;

    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'inventory line material does not exist';
    END IF;
    IF material_tracking_mode <> 'QUANTITY' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_material_quantity',
            MESSAGE = 'inventory quantity line requires a QUANTITY material';
    END IF;
    IF material_unit_id IS NULL THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_material_unit_required',
            MESSAGE = 'inventory quantity line material must have a unit';
    END IF;
    IF NEW.unit_id IS DISTINCT FROM material_unit_id THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_unit_matches_material',
            MESSAGE = 'inventory line unit must match material unit';
    END IF;

    PERFORM 1
    FROM public.catalog_materialcondition AS condition
    WHERE condition.id = NEW.condition_id
    FOR KEY SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'inventory line condition does not exist';
    END IF;

    PERFORM 1
    FROM public.locations_location AS location
    WHERE location.id = NEW.target_location_id
    FOR KEY SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'inventory line target location does not exist';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER inventory_line_quantity_guard_trg
BEFORE INSERT ON public.inventory_inventorytransactionline
FOR EACH ROW
EXECUTE FUNCTION public.inventory_line_quantity_guard();

CREATE OR REPLACE FUNCTION public.inventory_balance_quantity_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    material_tracking_mode varchar(10);
    location_active boolean;
    location_can_hold_stock boolean;
BEGIN
    SELECT material.tracking_mode
    INTO material_tracking_mode
    FROM public.catalog_material AS material
    WHERE material.id = NEW.material_id
    FOR SHARE;

    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'stock balance material does not exist';
    END IF;
    IF material_tracking_mode <> 'QUANTITY' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_balance_material_quantity',
            MESSAGE = 'stock balance requires a QUANTITY material';
    END IF;

    IF NEW.quantity > 0 THEN
        SELECT location.active, location.can_hold_stock
        INTO location_active, location_can_hold_stock
        FROM public.locations_location AS location
        WHERE location.id = NEW.location_id
        FOR SHARE;

        IF NOT FOUND THEN
            RAISE EXCEPTION USING
                ERRCODE = '23503',
                MESSAGE = 'stock balance location does not exist';
        END IF;
        IF NOT location_active OR NOT location_can_hold_stock THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_balance_positive_location',
                MESSAGE = 'positive stock balance requires an active stock-holding location';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER inventory_balance_quantity_guard_trg
BEFORE INSERT OR UPDATE ON public.inventory_stockbalance
FOR EACH ROW
EXECUTE FUNCTION public.inventory_balance_quantity_guard();

CREATE OR REPLACE FUNCTION public.inventory_material_tracking_mode_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.tracking_mode IS DISTINCT FROM OLD.tracking_mode
       AND (
           EXISTS (
               SELECT 1
               FROM public.inventory_inventorytransactionline AS line
               WHERE line.material_id = OLD.id
           )
           OR EXISTS (
               SELECT 1
               FROM public.inventory_stockbalance AS balance
               WHERE balance.material_id = OLD.id
           )
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_material_tracking_mode_history',
            MESSAGE = 'material tracking mode cannot change after inventory history';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER inventory_material_tracking_mode_guard_trg
BEFORE UPDATE OF tracking_mode ON public.catalog_material
FOR EACH ROW
EXECUTE FUNCTION public.inventory_material_tracking_mode_guard();

CREATE OR REPLACE FUNCTION public.inventory_location_positive_stock_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF (
        (OLD.active AND NOT NEW.active)
        OR (OLD.can_hold_stock AND NOT NEW.can_hold_stock)
    ) AND EXISTS (
        SELECT 1
        FROM public.inventory_stockbalance AS balance
        WHERE balance.location_id = OLD.id
          AND balance.quantity > 0
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_location_positive_stock',
            MESSAGE = 'location with positive stock cannot be deactivated or stop holding stock';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER inventory_location_positive_stock_guard_trg
BEFORE UPDATE OF active, can_hold_stock ON public.locations_location
FOR EACH ROW
EXECUTE FUNCTION public.inventory_location_positive_stock_guard();
"""


KERNEL_GUARD_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS inventory_location_positive_stock_guard_trg
    ON public.locations_location;
DROP FUNCTION IF EXISTS public.inventory_location_positive_stock_guard();

DROP TRIGGER IF EXISTS inventory_material_tracking_mode_guard_trg
    ON public.catalog_material;
DROP FUNCTION IF EXISTS public.inventory_material_tracking_mode_guard();

DROP TRIGGER IF EXISTS inventory_balance_quantity_guard_trg
    ON public.inventory_stockbalance;
DROP FUNCTION IF EXISTS public.inventory_balance_quantity_guard();

DROP TRIGGER IF EXISTS inventory_line_quantity_guard_trg
    ON public.inventory_inventorytransactionline;
DROP FUNCTION IF EXISTS public.inventory_line_quantity_guard();

DROP TRIGGER IF EXISTS inventory_tx_requires_line_trg
    ON public.inventory_inventorytransaction;
DROP FUNCTION IF EXISTS public.inventory_tx_requires_line_guard();

DROP TRIGGER IF EXISTS inventory_line_immutable_trg
    ON public.inventory_inventorytransactionline;
DROP TRIGGER IF EXISTS inventory_tx_immutable_trg
    ON public.inventory_inventorytransaction;
DROP FUNCTION IF EXISTS public.inventory_ledger_immutability_guard();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_seed_material_conditions'),
        ('inventory', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField()),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Stok girişi')], max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acting_user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransactionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_transaction_lines', to='catalog.materialcondition')),
                ('material', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_transaction_lines', to='catalog.material')),
                ('source_location', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_lines_as_source', to='locations.location')),
                ('target_location', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_lines_as_target', to='locations.location')),
                ('transaction', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='lines', to='inventory.inventorytransaction')),
                ('unit', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_transaction_lines', to='catalog.unitofmeasure')),
            ],
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='stock_balances', to='catalog.materialcondition')),
                ('location', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='stock_balances', to='locations.location')),
                ('material', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='stock_balances', to='catalog.material')),
            ],
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['occurred_at'], name='inventory_tx_occurred_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['acting_user', 'occurred_at'], name='inventory_tx_actor_occ_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.UniqueConstraint(fields=('operation_id',), name='inventory_tx_operation_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('request_fingerprint__regex', '^[0-9a-f]{64}$')), name='inventory_tx_fingerprint_hex'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('transaction_type', 'RECEIPT')), name='inventory_tx_type_receipt_only'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransactionline',
            constraint=models.UniqueConstraint(fields=('transaction', 'line_number'), name='inventory_line_tx_num_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransactionline',
            constraint=models.CheckConstraint(condition=models.Q(('line_number__gt', 0)), name='inventory_line_num_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransactionline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0'))), name='inventory_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransactionline',
            constraint=models.CheckConstraint(condition=models.Q(('source_location__isnull', True)), name='inventory_line_receipt_source_null'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['location'], name='inventory_bal_location_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('material', 'location', 'condition'), name='inventory_bal_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', Decimal('0'))), name='inventory_bal_qty_nonnegative'),
        ),
        migrations.RunSQL(
            sql=KERNEL_GUARD_SQL,
            reverse_sql=KERNEL_GUARD_REVERSE_SQL,
        ),
    ]
