# Generated by Django 5.2.17 on 2026-09-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_quantity_inventory_kernel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventorytransaction",
            options={"permissions": [("receive_stock", "Can receive stock")]},
        ),
    ]
