# Generated by Django 5.2.17 on 2026-09-12 10:10

import django.db.models.deletion
from django.db import migrations, models


PRE_MIGRATION_ASSERTIONS_SQL = r"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.inventory_inventorytransaction
        WHERE transaction_type <> 'RECEIPT'
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_issue_precheck_receipt_headers',
            MESSAGE = 'pre-4.2A inventory headers must all be RECEIPT';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.inventory_inventorytransactionline
        WHERE source_location_id IS NOT NULL
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_issue_precheck_null_sources',
            MESSAGE = 'pre-4.2A inventory lines must have null source locations';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.inventory_inventorytransactionline
        WHERE target_location_id IS NULL
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_issue_precheck_present_targets',
            MESSAGE = 'pre-4.2A inventory lines must have target locations';
    END IF;
END;
$$;
"""


ISSUE_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION public.inventory_tx_requires_line_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    line_count bigint;
BEGIN
    SELECT count(*)
    INTO line_count
    FROM public.inventory_inventorytransactionline AS line
    WHERE line.transaction_id = NEW.id;

    IF NEW.transaction_type = 'RECEIPT' AND line_count < 1 THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_tx_requires_line',
            MESSAGE = 'inventory transaction must contain at least one line';
    END IF;

    IF NEW.transaction_type = 'ISSUE' AND line_count <> 1 THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_issue_requires_one_line',
            MESSAGE = 'ISSUE transaction must contain exactly one line';
    END IF;

    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.inventory_issue_line_cardinality_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    parent_transaction_type varchar(32);
    line_count bigint;
BEGIN
    SELECT tx.transaction_type
    INTO parent_transaction_type
    FROM public.inventory_inventorytransaction AS tx
    WHERE tx.id = NEW.transaction_id;

    IF parent_transaction_type = 'ISSUE' THEN
        SELECT count(*)
        INTO line_count
        FROM public.inventory_inventorytransactionline AS line
        WHERE line.transaction_id = NEW.transaction_id;

        IF line_count <> 1 THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_issue_requires_one_line',
                MESSAGE = 'ISSUE transaction must contain exactly one line';
        END IF;
    END IF;

    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER inventory_issue_line_cardinality_trg
AFTER INSERT ON public.inventory_inventorytransactionline
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION public.inventory_issue_line_cardinality_guard();

CREATE OR REPLACE FUNCTION public.inventory_line_quantity_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    material_tracking_mode varchar(10);
    material_unit_id uuid;
    parent_transaction_type varchar(32);
BEGIN
    SELECT material.tracking_mode, material.unit_id
    INTO material_tracking_mode, material_unit_id
    FROM public.catalog_material AS material
    WHERE material.id = NEW.material_id
    FOR SHARE;

    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'inventory line material does not exist';
    END IF;
    IF material_tracking_mode <> 'QUANTITY' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_material_quantity',
            MESSAGE = 'inventory quantity line requires a QUANTITY material';
    END IF;
    IF material_unit_id IS NULL THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_material_unit_required',
            MESSAGE = 'inventory quantity line material must have a unit';
    END IF;
    IF NEW.unit_id IS DISTINCT FROM material_unit_id THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_unit_matches_material',
            MESSAGE = 'inventory line unit must match material unit';
    END IF;

    PERFORM 1
    FROM public.catalog_materialcondition AS condition
    WHERE condition.id = NEW.condition_id
    FOR KEY SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'inventory line condition does not exist';
    END IF;

    SELECT tx.transaction_type
    INTO parent_transaction_type
    FROM public.inventory_inventorytransaction AS tx
    WHERE tx.id = NEW.transaction_id
    FOR KEY SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'inventory line transaction does not exist';
    END IF;

    IF parent_transaction_type = 'RECEIPT' THEN
        IF NEW.source_location_id IS NOT NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_receipt_shape',
                MESSAGE = 'RECEIPT line source location must be null';
        END IF;
        IF NEW.target_location_id IS NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_receipt_shape',
                MESSAGE = 'RECEIPT line target location is required';
        END IF;

        PERFORM 1
        FROM public.locations_location AS location
        WHERE location.id = NEW.target_location_id
        FOR KEY SHARE;
        IF NOT FOUND THEN
            RAISE EXCEPTION USING
                ERRCODE = '23503',
                MESSAGE = 'inventory line target location does not exist';
        END IF;
    ELSIF parent_transaction_type = 'ISSUE' THEN
        IF NEW.source_location_id IS NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_issue_shape',
                MESSAGE = 'ISSUE line source location is required';
        END IF;
        IF NEW.target_location_id IS NOT NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_issue_shape',
                MESSAGE = 'ISSUE line target location must be null';
        END IF;

        PERFORM 1
        FROM public.locations_location AS location
        WHERE location.id = NEW.source_location_id
        FOR KEY SHARE;
        IF NOT FOUND THEN
            RAISE EXCEPTION USING
                ERRCODE = '23503',
                MESSAGE = 'inventory line source location does not exist';
        END IF;
    ELSE
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_transaction_type',
            MESSAGE = 'inventory line transaction type is not supported';
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.inventory_issue_context_type_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    parent_transaction_type varchar(32);
BEGIN
    SELECT tx.transaction_type
    INTO parent_transaction_type
    FROM public.inventory_inventorytransaction AS tx
    WHERE tx.id = NEW.transaction_id
    FOR KEY SHARE;

    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'issue context transaction does not exist';
    END IF;
    IF parent_transaction_type <> 'ISSUE' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_issue_context_transaction_type',
            MESSAGE = 'IssueContext requires an ISSUE transaction';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER inventory_issue_context_type_trg
BEFORE INSERT ON public.inventory_issuecontext
FOR EACH ROW
EXECUTE FUNCTION public.inventory_issue_context_type_guard();

CREATE TRIGGER inventory_issue_context_immutable_trg
BEFORE UPDATE OR DELETE ON public.inventory_issuecontext
FOR EACH ROW
EXECUTE FUNCTION public.inventory_ledger_immutability_guard();

CREATE OR REPLACE FUNCTION public.inventory_issue_requires_context_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.transaction_type = 'ISSUE'
       AND NOT EXISTS (
           SELECT 1
           FROM public.inventory_issuecontext AS issue_context
           WHERE issue_context.transaction_id = NEW.id
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_issue_requires_context',
            MESSAGE = 'ISSUE transaction must contain exactly one IssueContext';
    END IF;

    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER inventory_issue_requires_context_trg
AFTER INSERT ON public.inventory_inventorytransaction
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION public.inventory_issue_requires_context_guard();
"""


ISSUE_GUARD_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS inventory_issue_requires_context_trg
    ON public.inventory_inventorytransaction;
DROP FUNCTION IF EXISTS public.inventory_issue_requires_context_guard();

DROP TRIGGER IF EXISTS inventory_issue_context_immutable_trg
    ON public.inventory_issuecontext;
DROP TRIGGER IF EXISTS inventory_issue_context_type_trg
    ON public.inventory_issuecontext;
DROP FUNCTION IF EXISTS public.inventory_issue_context_type_guard();

DROP TRIGGER IF EXISTS inventory_issue_line_cardinality_trg
    ON public.inventory_inventorytransactionline;
DROP FUNCTION IF EXISTS public.inventory_issue_line_cardinality_guard();

CREATE OR REPLACE FUNCTION public.inventory_tx_requires_line_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM public.inventory_inventorytransactionline AS line
        WHERE line.transaction_id = NEW.id
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_tx_requires_line',
            MESSAGE = 'inventory transaction must contain at least one line';
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.inventory_line_quantity_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    material_tracking_mode varchar(10);
    material_unit_id uuid;
BEGIN
    SELECT material.tracking_mode, material.unit_id
    INTO material_tracking_mode, material_unit_id
    FROM public.catalog_material AS material
    WHERE material.id = NEW.material_id
    FOR SHARE;

    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'inventory line material does not exist';
    END IF;
    IF material_tracking_mode <> 'QUANTITY' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_material_quantity',
            MESSAGE = 'inventory quantity line requires a QUANTITY material';
    END IF;
    IF material_unit_id IS NULL THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_material_unit_required',
            MESSAGE = 'inventory quantity line material must have a unit';
    END IF;
    IF NEW.unit_id IS DISTINCT FROM material_unit_id THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_unit_matches_material',
            MESSAGE = 'inventory line unit must match material unit';
    END IF;

    PERFORM 1
    FROM public.catalog_materialcondition AS condition
    WHERE condition.id = NEW.condition_id
    FOR KEY SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'inventory line condition does not exist';
    END IF;

    PERFORM 1
    FROM public.locations_location AS location
    WHERE location.id = NEW.target_location_id
    FOR KEY SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'inventory line target location does not exist';
    END IF;

    RETURN NEW;
END;
$$;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_employee"),
        ("inventory", "0003_alter_inventorytransaction_options"),
    ]

    operations = [
        migrations.RunSQL(
            sql=PRE_MIGRATION_ASSERTIONS_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveConstraint(
            model_name="inventorytransaction",
            name="inventory_tx_type_receipt_only",
        ),
        migrations.RemoveConstraint(
            model_name="inventorytransactionline",
            name="inventory_line_receipt_source_null",
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("RECEIPT", "Stok girişi"), ("ISSUE", "Stok çıkışı")],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorytransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(transaction_type__in=["RECEIPT", "ISSUE"]),
                name="inventory_tx_type_receipt_or_issue",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransactionline",
            name="target_location",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="inventory_lines_as_target",
                to="locations.location",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorytransactionline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_location__isnull", False),
                    ("target_location__isnull", False),
                    _connector="OR",
                ),
                name="inventory_line_source_or_target_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorytransactionline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_location__isnull", True),
                    ("target_location__isnull", True),
                    models.Q(
                        ("source_location", models.F("target_location")),
                        _negated=True,
                    ),
                    _connector="OR",
                ),
                name="inventory_line_source_ne_target",
            ),
        ),
        migrations.CreateModel(
            name="IssueContext",
            fields=[
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        related_name="issue_context",
                        serialize=False,
                        to="inventory.inventorytransaction",
                    ),
                ),
                ("receiver_first_name_snapshot", models.CharField(max_length=150)),
                ("receiver_last_name_snapshot", models.CharField(max_length=150)),
                ("receiver_employee_number_snapshot", models.CharField(max_length=64)),
                ("production_line_code_snapshot", models.CharField(max_length=64)),
                ("production_line_name_snapshot", models.CharField(max_length=255)),
                ("usage_location_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "production_line",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="issue_contexts",
                        to="inventory.productionline",
                    ),
                ),
                (
                    "receiver_employee",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="issue_contexts",
                        to="accounts.employee",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["receiver_employee"],
                        name="inventory_issue_receiver_idx",
                    ),
                    models.Index(
                        fields=["production_line"],
                        name="inventory_issue_prodline_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("receiver_first_name_snapshot__regex", r"^\s*$"),
                            _negated=True,
                        ),
                        name="inventory_issue_receiver_first_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("receiver_last_name_snapshot__regex", r"^\s*$"),
                            _negated=True,
                        ),
                        name="inventory_issue_receiver_last_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("receiver_employee_number_snapshot__regex", r"^\s*$"),
                            _negated=True,
                        ),
                        name="inventory_issue_receiver_number_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("production_line_code_snapshot__regex", r"^\s*$"),
                            _negated=True,
                        ),
                        name="inventory_issue_line_code_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("production_line_name_snapshot__regex", r"^\s*$"),
                            _negated=True,
                        ),
                        name="inventory_issue_line_name_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("usage_location_text__regex", r"^\s*$"),
                            _negated=True,
                        ),
                        name="inventory_issue_usage_nonblank",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql=ISSUE_GUARD_SQL,
            reverse_sql=ISSUE_GUARD_REVERSE_SQL,
        ),
    ]
