# Generated by Django 5.2.17 on 2026-09-12

from django.db import migrations, models


PRE_MIGRATION_ASSERTIONS_SQL = r"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.inventory_inventorytransaction
        WHERE transaction_type NOT IN ('RECEIPT', 'ISSUE', 'RETURN')
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_transfer_precheck_supported_headers',
            MESSAGE = 'pre-4.5 inventory headers must be RECEIPT, ISSUE, or RETURN';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.inventory_inventorytransactionline AS line
        JOIN public.inventory_inventorytransaction AS tx
          ON tx.id = line.transaction_id
        WHERE (tx.transaction_type = 'RECEIPT'
               AND (line.source_location_id IS NOT NULL
                    OR line.target_location_id IS NULL
                    OR line.original_issue_line_id IS NOT NULL))
           OR (tx.transaction_type = 'ISSUE'
               AND (line.source_location_id IS NULL
                    OR line.target_location_id IS NOT NULL
                    OR line.original_issue_line_id IS NOT NULL))
           OR (tx.transaction_type = 'RETURN'
               AND (line.source_location_id IS NOT NULL
                    OR line.target_location_id IS NULL
                    OR line.original_issue_line_id IS NULL))
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_transfer_precheck_line_shapes',
            MESSAGE = 'pre-4.5 RECEIPT, ISSUE, or RETURN line shape is invalid';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.inventory_issuecontext AS issue_context
        JOIN public.inventory_inventorytransaction AS tx
          ON tx.id = issue_context.transaction_id
        WHERE tx.transaction_type <> 'ISSUE'
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_transfer_precheck_issue_context_type',
            MESSAGE = 'IssueContext must belong only to an ISSUE transaction';
    END IF;
END;
$$;
"""


TRANSFER_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION public.inventory_tx_requires_line_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    line_count bigint;
BEGIN
    SELECT count(*)
    INTO line_count
    FROM public.inventory_inventorytransactionline AS line
    WHERE line.transaction_id = NEW.id;

    IF NEW.transaction_type = 'RECEIPT' AND line_count < 1 THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_tx_requires_line',
            MESSAGE = 'inventory transaction must contain at least one line';
    END IF;

    IF NEW.transaction_type = 'ISSUE' AND line_count <> 1 THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_issue_requires_one_line',
            MESSAGE = 'ISSUE transaction must contain exactly one line';
    END IF;

    IF NEW.transaction_type = 'RETURN' AND line_count <> 1 THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_return_requires_one_line',
            MESSAGE = 'RETURN transaction must contain exactly one line';
    END IF;

    IF NEW.transaction_type = 'TRANSFER' AND line_count <> 1 THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_transfer_requires_one_line',
            MESSAGE = 'TRANSFER transaction must contain exactly one line';
    END IF;

    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.inventory_issue_line_cardinality_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    parent_transaction_type varchar(32);
    line_count bigint;
BEGIN
    SELECT tx.transaction_type
    INTO parent_transaction_type
    FROM public.inventory_inventorytransaction AS tx
    WHERE tx.id = NEW.transaction_id;

    IF parent_transaction_type IN ('ISSUE', 'RETURN', 'TRANSFER') THEN
        SELECT count(*)
        INTO line_count
        FROM public.inventory_inventorytransactionline AS line
        WHERE line.transaction_id = NEW.transaction_id;

        IF parent_transaction_type = 'ISSUE' AND line_count <> 1 THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_issue_requires_one_line',
                MESSAGE = 'ISSUE transaction must contain exactly one line';
        END IF;

        IF parent_transaction_type = 'RETURN' AND line_count <> 1 THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_return_requires_one_line',
                MESSAGE = 'RETURN transaction must contain exactly one line';
        END IF;

        IF parent_transaction_type = 'TRANSFER' AND line_count <> 1 THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_transfer_requires_one_line',
                MESSAGE = 'TRANSFER transaction must contain exactly one line';
        END IF;
    END IF;

    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.inventory_line_quantity_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    material_tracking_mode varchar(10);
    material_unit_id uuid;
    parent_transaction_type varchar(32);
    original_transaction_type varchar(32);
    original_material_id uuid;
    original_unit_id uuid;
    original_condition_id uuid;
    original_quantity numeric(18, 3);
    returned_quantity numeric(18, 3);
BEGIN
    SELECT material.tracking_mode, material.unit_id
    INTO material_tracking_mode, material_unit_id
    FROM public.catalog_material AS material
    WHERE material.id = NEW.material_id
    FOR SHARE;

    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'inventory line material does not exist';
    END IF;
    IF material_tracking_mode <> 'QUANTITY' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_material_quantity',
            MESSAGE = 'inventory quantity line requires a QUANTITY material';
    END IF;
    IF material_unit_id IS NULL THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_material_unit_required',
            MESSAGE = 'inventory quantity line material must have a unit';
    END IF;
    IF NEW.unit_id IS DISTINCT FROM material_unit_id THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_unit_matches_material',
            MESSAGE = 'inventory line unit must match material unit';
    END IF;

    SELECT tx.transaction_type
    INTO parent_transaction_type
    FROM public.inventory_inventorytransaction AS tx
    WHERE tx.id = NEW.transaction_id
    FOR KEY SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'inventory line transaction does not exist';
    END IF;

    IF parent_transaction_type = 'TRANSFER' THEN
        IF NEW.source_location_id IS NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_transfer_shape',
                MESSAGE = 'TRANSFER line source location is required';
        END IF;
        IF NEW.target_location_id IS NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_transfer_shape',
                MESSAGE = 'TRANSFER line target location is required';
        END IF;
        IF NEW.original_issue_line_id IS NOT NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_transfer_shape',
                MESSAGE = 'TRANSFER line original issue line must be null';
        END IF;
        IF NEW.source_location_id = NEW.target_location_id THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_source_ne_target',
                MESSAGE = 'TRANSFER line source and target must differ';
        END IF;

        IF NEW.source_location_id < NEW.target_location_id THEN
            PERFORM 1
            FROM public.locations_location AS location
            WHERE location.id = NEW.source_location_id
            FOR KEY SHARE;
            IF NOT FOUND THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23503',
                    MESSAGE = 'inventory line source location does not exist';
            END IF;
            PERFORM 1
            FROM public.locations_location AS location
            WHERE location.id = NEW.target_location_id
            FOR KEY SHARE;
            IF NOT FOUND THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23503',
                    MESSAGE = 'inventory line target location does not exist';
            END IF;
        ELSE
            PERFORM 1
            FROM public.locations_location AS location
            WHERE location.id = NEW.target_location_id
            FOR KEY SHARE;
            IF NOT FOUND THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23503',
                    MESSAGE = 'inventory line target location does not exist';
            END IF;
            PERFORM 1
            FROM public.locations_location AS location
            WHERE location.id = NEW.source_location_id
            FOR KEY SHARE;
            IF NOT FOUND THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23503',
                    MESSAGE = 'inventory line source location does not exist';
            END IF;
        END IF;

        PERFORM 1
        FROM public.catalog_materialcondition AS condition
        WHERE condition.id = NEW.condition_id
        FOR KEY SHARE;
        IF NOT FOUND THEN
            RAISE EXCEPTION USING
                ERRCODE = '23503',
                MESSAGE = 'inventory line condition does not exist';
        END IF;

        RETURN NEW;
    END IF;

    PERFORM 1
    FROM public.catalog_materialcondition AS condition
    WHERE condition.id = NEW.condition_id
    FOR KEY SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'inventory line condition does not exist';
    END IF;

    IF parent_transaction_type = 'RECEIPT' THEN
        IF NEW.source_location_id IS NOT NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_receipt_shape',
                MESSAGE = 'RECEIPT line source location must be null';
        END IF;
        IF NEW.target_location_id IS NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_receipt_shape',
                MESSAGE = 'RECEIPT line target location is required';
        END IF;
        IF NEW.original_issue_line_id IS NOT NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_receipt_shape',
                MESSAGE = 'RECEIPT line original issue line must be null';
        END IF;

        PERFORM 1
        FROM public.locations_location AS location
        WHERE location.id = NEW.target_location_id
        FOR KEY SHARE;
        IF NOT FOUND THEN
            RAISE EXCEPTION USING
                ERRCODE = '23503',
                MESSAGE = 'inventory line target location does not exist';
        END IF;
    ELSIF parent_transaction_type = 'ISSUE' THEN
        IF NEW.source_location_id IS NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_issue_shape',
                MESSAGE = 'ISSUE line source location is required';
        END IF;
        IF NEW.target_location_id IS NOT NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_issue_shape',
                MESSAGE = 'ISSUE line target location must be null';
        END IF;
        IF NEW.original_issue_line_id IS NOT NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_issue_shape',
                MESSAGE = 'ISSUE line original issue line must be null';
        END IF;

        PERFORM 1
        FROM public.locations_location AS location
        WHERE location.id = NEW.source_location_id
        FOR KEY SHARE;
        IF NOT FOUND THEN
            RAISE EXCEPTION USING
                ERRCODE = '23503',
                MESSAGE = 'inventory line source location does not exist';
        END IF;
    ELSIF parent_transaction_type = 'RETURN' THEN
        IF NEW.source_location_id IS NOT NULL
           OR NEW.target_location_id IS NULL
           OR NEW.original_issue_line_id IS NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_return_shape',
                MESSAGE = 'RETURN line requires null source, target, and original issue line';
        END IF;

        PERFORM 1
        FROM public.locations_location AS location
        WHERE location.id = NEW.target_location_id
        FOR KEY SHARE;
        IF NOT FOUND THEN
            RAISE EXCEPTION USING
                ERRCODE = '23503',
                MESSAGE = 'inventory line target location does not exist';
        END IF;

        SELECT original_tx.transaction_type,
               original_line.material_id,
               original_line.unit_id,
               original_line.condition_id,
               original_line.quantity
        INTO original_transaction_type,
             original_material_id,
             original_unit_id,
             original_condition_id,
             original_quantity
        FROM public.inventory_inventorytransactionline AS original_line
        JOIN public.inventory_inventorytransaction AS original_tx
          ON original_tx.id = original_line.transaction_id
        WHERE original_line.id = NEW.original_issue_line_id
        FOR UPDATE OF original_line;

        IF NOT FOUND OR original_transaction_type <> 'ISSUE' THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_return_original_issue_line',
                MESSAGE = 'RETURN original issue line must belong to an ISSUE transaction';
        END IF;

        IF NEW.material_id IS DISTINCT FROM original_material_id THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_return_material_matches_issue',
                MESSAGE = 'RETURN material must match original ISSUE line';
        END IF;
        IF NEW.unit_id IS DISTINCT FROM original_unit_id THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_return_unit_matches_issue',
                MESSAGE = 'RETURN unit must match original ISSUE line';
        END IF;
        IF NEW.condition_id IS DISTINCT FROM original_condition_id THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_return_condition_matches_issue',
                MESSAGE = 'RETURN condition must match original ISSUE line';
        END IF;

        SELECT COALESCE(sum(return_line.quantity), 0)
        INTO returned_quantity
        FROM public.inventory_inventorytransactionline AS return_line
        JOIN public.inventory_inventorytransaction AS return_tx
          ON return_tx.id = return_line.transaction_id
        WHERE return_line.original_issue_line_id = NEW.original_issue_line_id
          AND return_tx.transaction_type = 'RETURN';

        IF returned_quantity + NEW.quantity > original_quantity THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_return_cumulative_quantity_cap',
                MESSAGE = 'cumulative RETURN quantity cannot exceed original ISSUE quantity';
        END IF;
    ELSE
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_transaction_type',
            MESSAGE = 'inventory line transaction type is not supported';
    END IF;

    RETURN NEW;
END;
$$;
"""


TRANSFER_GUARD_REVERSE_SQL = r"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.inventory_inventorytransaction
        WHERE transaction_type = 'TRANSFER'
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_transfer_reverse_requires_no_data',
            MESSAGE = 'cannot reverse quantity TRANSFER kernel while TRANSFER data exists';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.inventory_tx_requires_line_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    line_count bigint;
BEGIN
    SELECT count(*)
    INTO line_count
    FROM public.inventory_inventorytransactionline AS line
    WHERE line.transaction_id = NEW.id;

    IF NEW.transaction_type = 'RECEIPT' AND line_count < 1 THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_tx_requires_line',
            MESSAGE = 'inventory transaction must contain at least one line';
    END IF;

    IF NEW.transaction_type = 'ISSUE' AND line_count <> 1 THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_issue_requires_one_line',
            MESSAGE = 'ISSUE transaction must contain exactly one line';
    END IF;

    IF NEW.transaction_type = 'RETURN' AND line_count <> 1 THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_return_requires_one_line',
            MESSAGE = 'RETURN transaction must contain exactly one line';
    END IF;

    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.inventory_issue_line_cardinality_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    parent_transaction_type varchar(32);
    line_count bigint;
BEGIN
    SELECT tx.transaction_type
    INTO parent_transaction_type
    FROM public.inventory_inventorytransaction AS tx
    WHERE tx.id = NEW.transaction_id;

    IF parent_transaction_type IN ('ISSUE', 'RETURN') THEN
        SELECT count(*)
        INTO line_count
        FROM public.inventory_inventorytransactionline AS line
        WHERE line.transaction_id = NEW.transaction_id;

        IF parent_transaction_type = 'ISSUE' AND line_count <> 1 THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_issue_requires_one_line',
                MESSAGE = 'ISSUE transaction must contain exactly one line';
        END IF;

        IF parent_transaction_type = 'RETURN' AND line_count <> 1 THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_return_requires_one_line',
                MESSAGE = 'RETURN transaction must contain exactly one line';
        END IF;
    END IF;

    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.inventory_line_quantity_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    material_tracking_mode varchar(10);
    material_unit_id uuid;
    parent_transaction_type varchar(32);
    original_transaction_type varchar(32);
    original_material_id uuid;
    original_unit_id uuid;
    original_condition_id uuid;
    original_quantity numeric(18, 3);
    returned_quantity numeric(18, 3);
BEGIN
    SELECT material.tracking_mode, material.unit_id
    INTO material_tracking_mode, material_unit_id
    FROM public.catalog_material AS material
    WHERE material.id = NEW.material_id
    FOR SHARE;

    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'inventory line material does not exist';
    END IF;
    IF material_tracking_mode <> 'QUANTITY' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_material_quantity',
            MESSAGE = 'inventory quantity line requires a QUANTITY material';
    END IF;
    IF material_unit_id IS NULL THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_material_unit_required',
            MESSAGE = 'inventory quantity line material must have a unit';
    END IF;
    IF NEW.unit_id IS DISTINCT FROM material_unit_id THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_unit_matches_material',
            MESSAGE = 'inventory line unit must match material unit';
    END IF;

    PERFORM 1
    FROM public.catalog_materialcondition AS condition
    WHERE condition.id = NEW.condition_id
    FOR KEY SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'inventory line condition does not exist';
    END IF;

    SELECT tx.transaction_type
    INTO parent_transaction_type
    FROM public.inventory_inventorytransaction AS tx
    WHERE tx.id = NEW.transaction_id
    FOR KEY SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23503',
            MESSAGE = 'inventory line transaction does not exist';
    END IF;

    IF parent_transaction_type = 'RECEIPT' THEN
        IF NEW.source_location_id IS NOT NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_receipt_shape',
                MESSAGE = 'RECEIPT line source location must be null';
        END IF;
        IF NEW.target_location_id IS NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_receipt_shape',
                MESSAGE = 'RECEIPT line target location is required';
        END IF;
        IF NEW.original_issue_line_id IS NOT NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_receipt_shape',
                MESSAGE = 'RECEIPT line original issue line must be null';
        END IF;

        PERFORM 1
        FROM public.locations_location AS location
        WHERE location.id = NEW.target_location_id
        FOR KEY SHARE;
        IF NOT FOUND THEN
            RAISE EXCEPTION USING
                ERRCODE = '23503',
                MESSAGE = 'inventory line target location does not exist';
        END IF;
    ELSIF parent_transaction_type = 'ISSUE' THEN
        IF NEW.source_location_id IS NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_issue_shape',
                MESSAGE = 'ISSUE line source location is required';
        END IF;
        IF NEW.target_location_id IS NOT NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_issue_shape',
                MESSAGE = 'ISSUE line target location must be null';
        END IF;
        IF NEW.original_issue_line_id IS NOT NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_issue_shape',
                MESSAGE = 'ISSUE line original issue line must be null';
        END IF;

        PERFORM 1
        FROM public.locations_location AS location
        WHERE location.id = NEW.source_location_id
        FOR KEY SHARE;
        IF NOT FOUND THEN
            RAISE EXCEPTION USING
                ERRCODE = '23503',
                MESSAGE = 'inventory line source location does not exist';
        END IF;
    ELSIF parent_transaction_type = 'RETURN' THEN
        IF NEW.source_location_id IS NOT NULL
           OR NEW.target_location_id IS NULL
           OR NEW.original_issue_line_id IS NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_return_shape',
                MESSAGE = 'RETURN line requires null source, target, and original issue line';
        END IF;

        PERFORM 1
        FROM public.locations_location AS location
        WHERE location.id = NEW.target_location_id
        FOR KEY SHARE;
        IF NOT FOUND THEN
            RAISE EXCEPTION USING
                ERRCODE = '23503',
                MESSAGE = 'inventory line target location does not exist';
        END IF;

        SELECT original_tx.transaction_type,
               original_line.material_id,
               original_line.unit_id,
               original_line.condition_id,
               original_line.quantity
        INTO original_transaction_type,
             original_material_id,
             original_unit_id,
             original_condition_id,
             original_quantity
        FROM public.inventory_inventorytransactionline AS original_line
        JOIN public.inventory_inventorytransaction AS original_tx
          ON original_tx.id = original_line.transaction_id
        WHERE original_line.id = NEW.original_issue_line_id
        FOR UPDATE OF original_line;

        IF NOT FOUND OR original_transaction_type <> 'ISSUE' THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_return_original_issue_line',
                MESSAGE = 'RETURN original issue line must belong to an ISSUE transaction';
        END IF;

        IF NEW.material_id IS DISTINCT FROM original_material_id THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_return_material_matches_issue',
                MESSAGE = 'RETURN material must match original ISSUE line';
        END IF;
        IF NEW.unit_id IS DISTINCT FROM original_unit_id THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_return_unit_matches_issue',
                MESSAGE = 'RETURN unit must match original ISSUE line';
        END IF;
        IF NEW.condition_id IS DISTINCT FROM original_condition_id THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_return_condition_matches_issue',
                MESSAGE = 'RETURN condition must match original ISSUE line';
        END IF;

        SELECT COALESCE(sum(return_line.quantity), 0)
        INTO returned_quantity
        FROM public.inventory_inventorytransactionline AS return_line
        JOIN public.inventory_inventorytransaction AS return_tx
          ON return_tx.id = return_line.transaction_id
        WHERE return_line.original_issue_line_id = NEW.original_issue_line_id
          AND return_tx.transaction_type = 'RETURN';

        IF returned_quantity + NEW.quantity > original_quantity THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_return_cumulative_quantity_cap',
                MESSAGE = 'cumulative RETURN quantity cannot exceed original ISSUE quantity';
        END IF;
    ELSE
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_transaction_type',
            MESSAGE = 'inventory line transaction type is not supported';
    END IF;

    RETURN NEW;
END;
$$;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_quantity_return_kernel"),
    ]

    operations = [
        migrations.RunSQL(
            sql=PRE_MIGRATION_ASSERTIONS_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveConstraint(
            model_name="inventorytransaction",
            name="inventory_tx_type_supported",
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("RECEIPT", "Stok girişi"),
                    ("ISSUE", "Stok çıkışı"),
                    ("RETURN", "Stok iadesi"),
                    ("TRANSFER", "Stok transferi"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorytransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    transaction_type__in=["RECEIPT", "ISSUE", "RETURN", "TRANSFER"]
                ),
                name="inventory_tx_type_supported",
            ),
        ),
        migrations.RunSQL(
            sql=TRANSFER_GUARD_SQL,
            reverse_sql=TRANSFER_GUARD_REVERSE_SQL,
        ),
        migrations.AlterModelOptions(
            name="inventorytransaction",
            options={
                "permissions": [
                    ("receive_stock", "Can receive stock"),
                    ("issue_stock", "Can issue stock"),
                    ("return_stock", "Can return stock"),
                    ("transfer_stock", "Can transfer stock"),
                ]
            },
        ),
    ]
