# Generated by Django 5.2.17 on 2026-09-13 08:38

import django.db.models.deletion
import importlib
from django.conf import settings
from django.db import migrations, models


_previous_kernel = importlib.import_module(
    "inventory.migrations.0007_quantity_transfer_kernel"
)

PRE_MIGRATION_ASSERTIONS_SQL = r"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.inventory_inventorytransaction
        WHERE transaction_type NOT IN ('RECEIPT', 'ISSUE', 'RETURN', 'TRANSFER')
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_correction_precheck_supported_headers',
            MESSAGE = 'pre-5.2 inventory headers must use the existing four transaction types';
    END IF;
END;
$$;
"""


def _controlled_correction_guard_sql():
    sql = _previous_kernel.TRANSFER_GUARD_SQL
    sql = sql.replace(
        """    IF NEW.transaction_type = 'TRANSFER' AND line_count <> 1 THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_transfer_requires_one_line',
            MESSAGE = 'TRANSFER transaction must contain exactly one line';
    END IF;
""",
        """    IF NEW.transaction_type = 'TRANSFER' AND line_count <> 1 THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_transfer_requires_one_line',
            MESSAGE = 'TRANSFER transaction must contain exactly one line';
    END IF;

    IF NEW.transaction_type = 'CONTROLLED_CORRECTION'
       AND line_count NOT IN (1, 2) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_correction_line_cardinality',
            MESSAGE = 'CONTROLLED_CORRECTION transaction must contain one or two lines';
    END IF;
""",
        1,
    )
    sql = sql.replace(
        "IF parent_transaction_type IN ('ISSUE', 'RETURN', 'TRANSFER') THEN",
        "IF parent_transaction_type IN ('ISSUE', 'RETURN', 'TRANSFER', 'CONTROLLED_CORRECTION') THEN",
        1,
    )
    sql = sql.replace(
        """        IF parent_transaction_type = 'TRANSFER' AND line_count <> 1 THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_transfer_requires_one_line',
                MESSAGE = 'TRANSFER transaction must contain exactly one line';
        END IF;
""",
        """        IF parent_transaction_type = 'TRANSFER' AND line_count <> 1 THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_transfer_requires_one_line',
                MESSAGE = 'TRANSFER transaction must contain exactly one line';
        END IF;

        IF parent_transaction_type = 'CONTROLLED_CORRECTION' THEN
            IF line_count NOT IN (1, 2) THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23514',
                    CONSTRAINT = 'inventory_correction_line_cardinality',
                    MESSAGE = 'CONTROLLED_CORRECTION transaction must contain one or two lines';
            END IF;

            IF line_count = 1 AND NOT EXISTS (
                SELECT 1
                FROM public.inventory_inventorytransactionline AS correction_line
                JOIN public.inventory_inventorytransactionline AS original_line
                  ON original_line.id = correction_line.corrected_line_id
                WHERE correction_line.transaction_id = NEW.transaction_id
                  AND correction_line.material_id = original_line.material_id
                  AND correction_line.condition_id = original_line.condition_id
                  AND COALESCE(
                        correction_line.source_location_id,
                        correction_line.target_location_id
                      ) IN (
                        original_line.source_location_id,
                        original_line.target_location_id
                      )
            ) THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23514',
                    CONSTRAINT = 'inventory_correction_quantity_shape',
                    MESSAGE = 'one-line correction must affect an original line bucket';
            END IF;

            IF line_count = 2 AND NOT EXISTS (
                SELECT 1
                FROM public.inventory_inventorytransactionline AS decrease_line
                JOIN public.inventory_inventorytransactionline AS increase_line
                  ON increase_line.transaction_id = decrease_line.transaction_id
                 AND increase_line.id <> decrease_line.id
                JOIN public.inventory_inventorytransactionline AS original_line
                  ON original_line.id = decrease_line.corrected_line_id
                WHERE decrease_line.transaction_id = NEW.transaction_id
                  AND decrease_line.source_location_id IS NOT NULL
                  AND decrease_line.target_location_id IS NULL
                  AND increase_line.source_location_id IS NULL
                  AND increase_line.target_location_id IS NOT NULL
                  AND decrease_line.corrected_line_id = increase_line.corrected_line_id
                  AND decrease_line.quantity = increase_line.quantity
                  AND decrease_line.material_id = original_line.material_id
                  AND decrease_line.condition_id = original_line.condition_id
                  AND decrease_line.source_location_id IN (
                        original_line.source_location_id,
                        original_line.target_location_id
                      )
                  AND (
                        increase_line.material_id <> decrease_line.material_id
                     OR increase_line.condition_id <> decrease_line.condition_id
                     OR increase_line.target_location_id <> decrease_line.source_location_id
                  )
            ) THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23514',
                    CONSTRAINT = 'inventory_correction_identity_shape',
                    MESSAGE = 'two-line correction must be one equal decrease/increase identity restatement';
            END IF;

            IF EXISTS (
                SELECT 1
                FROM public.inventory_inventorytransactionline AS original_line
                WHERE original_line.id = (
                    SELECT corrected_line_id
                    FROM public.inventory_inventorytransactionline
                    WHERE transaction_id = NEW.transaction_id
                    LIMIT 1
                )
                  AND (
                    SELECT COALESCE(SUM(
                        CASE
                            WHEN correction_line.source_location_id IS NOT NULL
                                THEN correction_line.quantity
                            WHEN correction_counts.line_count = 1
                                 AND correction_line.target_location_id IS NOT NULL
                                THEN -correction_line.quantity
                            ELSE 0
                        END
                    ), 0)
                    FROM public.inventory_inventorytransactionline AS correction_line
                    JOIN public.inventory_inventorytransaction AS correction_tx
                      ON correction_tx.id = correction_line.transaction_id
                    JOIN (
                        SELECT transaction_id, count(*) AS line_count
                        FROM public.inventory_inventorytransactionline
                        GROUP BY transaction_id
                    ) AS correction_counts
                      ON correction_counts.transaction_id = correction_line.transaction_id
                    WHERE correction_tx.transaction_type = 'CONTROLLED_CORRECTION'
                      AND correction_line.corrected_line_id = original_line.id
                  ) > original_line.quantity
            ) THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23514',
                    CONSTRAINT = 'inventory_correction_cumulative_floor',
                    MESSAGE = 'cumulative correction cannot imply a negative original quantity equivalent';
            END IF;
        END IF;
""",
        1,
    )
    sql = sql.replace(
        """    IF parent_transaction_type = 'TRANSFER' THEN
""",
        """    IF parent_transaction_type <> 'CONTROLLED_CORRECTION'
       AND NEW.corrected_line_id IS NOT NULL THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_noncorrection_lineage_null',
            MESSAGE = 'non-correction line corrected lineage must be null';
    END IF;

    IF parent_transaction_type = 'CONTROLLED_CORRECTION' THEN
        IF NEW.original_issue_line_id IS NOT NULL
           OR NEW.corrected_line_id IS NULL
           OR (NEW.source_location_id IS NULL) = (NEW.target_location_id IS NULL) THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_correction_line_shape',
                MESSAGE = 'correction line requires one direction and corrected lineage';
        END IF;

        SELECT original_tx.transaction_type
        INTO original_transaction_type
        FROM public.inventory_inventorytransactionline AS original_line
        JOIN public.inventory_inventorytransaction AS original_tx
          ON original_tx.id = original_line.transaction_id
        WHERE original_line.id = NEW.corrected_line_id
          AND original_line.corrected_line_id IS NULL
        FOR UPDATE OF original_line;

        IF NOT FOUND OR original_transaction_type = 'CONTROLLED_CORRECTION' THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_correction_canonical_lineage',
                MESSAGE = 'correction lineage must reference a canonical non-correction line';
        END IF;

        IF NEW.source_location_id IS NOT NULL AND NOT EXISTS (
            SELECT 1
            FROM public.inventory_inventorytransactionline AS original_line
            WHERE original_line.id = NEW.corrected_line_id
              AND original_line.material_id = NEW.material_id
              AND original_line.condition_id = NEW.condition_id
              AND NEW.source_location_id IN (
                    original_line.source_location_id,
                    original_line.target_location_id
                  )
        ) THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_correction_source_identity',
                MESSAGE = 'correction decrease must use an original line bucket';
        END IF;

        PERFORM 1
        FROM public.locations_location AS location
        WHERE location.id = COALESCE(NEW.source_location_id, NEW.target_location_id)
        FOR KEY SHARE;
        IF NOT FOUND THEN
            RAISE EXCEPTION USING
                ERRCODE = '23503',
                MESSAGE = 'correction line location does not exist';
        END IF;

        RETURN NEW;
    END IF;

    IF parent_transaction_type = 'TRANSFER' THEN
""",
        1,
    )
    return sql


CONTROLLED_CORRECTION_GUARD_SQL = _controlled_correction_guard_sql()
CONTROLLED_CORRECTION_GUARD_REVERSE_SQL = r"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.inventory_inventorytransaction
        WHERE transaction_type = 'CONTROLLED_CORRECTION'
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_correction_reverse_requires_no_data',
            MESSAGE = 'cannot reverse controlled correction kernel while correction data exists';
    END IF;
END;
$$;
""" + _previous_kernel.TRANSFER_GUARD_SQL


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_quantity_transfer_kernel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql=PRE_MIGRATION_ASSERTIONS_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'permissions': [('receive_stock', 'Can receive stock'), ('issue_stock', 'Can issue stock'), ('return_stock', 'Can return stock'), ('transfer_stock', 'Can transfer stock')]},
        ),
        migrations.RemoveConstraint(
            model_name='inventorytransaction',
            name='inventory_tx_type_supported',
        ),
        migrations.AddField(
            model_name='inventorytransactionline',
            name='corrected_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='correction_lines', to='inventory.inventorytransactionline'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('RECEIPT', 'Stok girişi'), ('ISSUE', 'Stok çıkışı'), ('RETURN', 'Stok iadesi'), ('TRANSFER', 'Stok transferi'), ('CONTROLLED_CORRECTION', 'Kontrollü düzeltme')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('transaction_type__in', ['RECEIPT', 'ISSUE', 'RETURN', 'TRANSFER', 'CONTROLLED_CORRECTION'])), name='inventory_tx_type_supported'),
        ),
        migrations.RunSQL(
            sql=CONTROLLED_CORRECTION_GUARD_SQL,
            reverse_sql=CONTROLLED_CORRECTION_GUARD_REVERSE_SQL,
        ),
    ]
