# Generated by Django 5.2.17 on 2026-09-13 15:54

import django.db.models.deletion
import importlib
import uuid
from decimal import Decimal
from django.db import migrations, models


_previous_kernel = importlib.import_module(
    "inventory.migrations.0008_alter_inventorytransaction_options_and_more"
)


PRE_GUARD_ASSERTIONS_SQL = r"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.inventory_inventorytransactionline
        WHERE serialized_asset_id IS NOT NULL
           OR quantity IS NULL
           OR unit_id IS NULL
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_serialized_precheck_quantity_lines',
            MESSAGE = 'pre-5.3 inventory lines must retain the valid quantity shape';
    END IF;

    IF EXISTS (SELECT 1 FROM public.inventory_serializedasset) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_serialized_precheck_no_assets',
            MESSAGE = 'serialized asset table must be empty before guards are installed';
    END IF;
END;
$$;
"""


def _replace_once(sql, old, new):
    if sql.count(old) != 1:
        raise RuntimeError("serialized guard source shape changed unexpectedly")
    return sql.replace(old, new, 1)


def _serialized_guard_sql():
    sql = _previous_kernel.CONTROLLED_CORRECTION_GUARD_SQL
    sql = _replace_once(
        sql,
        """    returned_quantity numeric(18, 3);
BEGIN
""",
        """    returned_quantity numeric(18, 3);
    asset_material_id uuid;
    asset_current_location_id uuid;
    asset_current_condition_id uuid;
    asset_current_state varchar(16);
BEGIN
""",
    )
    sql = _replace_once(
        sql,
        """    IF material_tracking_mode <> 'QUANTITY' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_material_quantity',
            MESSAGE = 'inventory quantity line requires a QUANTITY material';
    END IF;
    IF material_unit_id IS NULL THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_material_unit_required',
            MESSAGE = 'inventory quantity line material must have a unit';
    END IF;
    IF NEW.unit_id IS DISTINCT FROM material_unit_id THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_unit_matches_material',
            MESSAGE = 'inventory line unit must match material unit';
    END IF;
""",
        """    IF material_tracking_mode = 'QUANTITY' THEN
        IF NEW.serialized_asset_id IS NOT NULL
           OR NEW.quantity IS NULL
           OR NEW.unit_id IS NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_quantity_shape',
                MESSAGE = 'QUANTITY line requires quantity/unit and no serialized asset';
        END IF;
        IF material_unit_id IS NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_material_unit_required',
                MESSAGE = 'inventory quantity line material must have a unit';
        END IF;
        IF NEW.unit_id IS DISTINCT FROM material_unit_id THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_unit_matches_material',
                MESSAGE = 'inventory line unit must match material unit';
        END IF;
    ELSIF material_tracking_mode = 'SERIALIZED' THEN
        IF NEW.serialized_asset_id IS NULL
           AND NEW.quantity IS NOT NULL
           AND NEW.unit_id IS NOT NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_material_quantity',
                MESSAGE = 'inventory quantity line requires a QUANTITY material';
        END IF;
        IF NEW.serialized_asset_id IS NULL
           OR NEW.quantity IS NOT NULL
           OR NEW.unit_id IS NOT NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_serialized_shape',
                MESSAGE = 'SERIALIZED line requires an asset and null quantity/unit';
        END IF;

        SELECT asset.material_id,
               asset.current_location_id,
               asset.current_condition_id,
               asset.current_state
        INTO asset_material_id,
             asset_current_location_id,
             asset_current_condition_id,
             asset_current_state
        FROM public.inventory_serializedasset AS asset
        WHERE asset.id = NEW.serialized_asset_id
        FOR UPDATE;

        IF NOT FOUND THEN
            RAISE EXCEPTION USING
                ERRCODE = '23503',
                MESSAGE = 'serialized inventory line asset does not exist';
        END IF;
        IF NEW.material_id IS DISTINCT FROM asset_material_id THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_asset_material_match',
                MESSAGE = 'serialized line material must match asset material';
        END IF;
    ELSE
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_line_material_tracking_mode',
            MESSAGE = 'inventory line material tracking mode is unsupported';
    END IF;
""",
    )
    sql = _replace_once(
        sql,
        """    IF parent_transaction_type <> 'CONTROLLED_CORRECTION'
       AND NEW.corrected_line_id IS NOT NULL THEN
""",
        """    IF material_tracking_mode = 'QUANTITY'
       AND parent_transaction_type = 'RECEIPT'
       AND EXISTS (
           SELECT 1
           FROM public.inventory_inventorytransactionline AS other_line
           WHERE other_line.transaction_id = NEW.transaction_id
             AND other_line.serialized_asset_id IS NOT NULL
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_receipt_tracking_mode_mixed',
            MESSAGE = 'quantity and serialized lines cannot share a RECEIVE transaction';
    END IF;

    IF material_tracking_mode = 'SERIALIZED' THEN
        IF parent_transaction_type <> 'RECEIPT'
           OR NEW.source_location_id IS NOT NULL
           OR NEW.target_location_id IS NULL
           OR NEW.original_issue_line_id IS NOT NULL
           OR NEW.corrected_line_id IS NOT NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_line_serialized_receipt_shape',
                MESSAGE = 'serialized first slice permits only a source-null RECEIVE line';
        END IF;
        IF EXISTS (
            SELECT 1
            FROM public.inventory_inventorytransactionline AS other_line
            WHERE other_line.transaction_id = NEW.transaction_id
        ) THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_serialized_receipt_one_line',
                MESSAGE = 'serialized RECEIVE must contain exactly one line';
        END IF;
        IF EXISTS (
            SELECT 1
            FROM public.inventory_inventorytransactionline AS prior_line
            WHERE prior_line.serialized_asset_id = NEW.serialized_asset_id
        ) THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_serialized_asset_received_once',
                MESSAGE = 'serialized asset can be established by exactly one RECEIVE';
        END IF;
        IF NEW.target_location_id IS DISTINCT FROM asset_current_location_id
           OR NEW.condition_id IS DISTINCT FROM asset_current_condition_id
           OR asset_current_state <> 'IN_STOCK' THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'inventory_serialized_receipt_projection_match',
                MESSAGE = 'serialized RECEIVE line must match the asset projection';
        END IF;
        RETURN NEW;
    END IF;

    IF parent_transaction_type <> 'CONTROLLED_CORRECTION'
       AND NEW.corrected_line_id IS NOT NULL THEN
""",
    )
    return sql + r"""

CREATE OR REPLACE FUNCTION public.inventory_serialized_asset_integrity_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    material_tracking_mode varchar(10);
    location_active boolean;
    location_can_hold_stock boolean;
    condition_active boolean;
BEGIN
    SELECT material.tracking_mode
    INTO material_tracking_mode
    FROM public.catalog_material AS material
    WHERE material.id = NEW.material_id
    FOR SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'serialized asset material does not exist';
    END IF;
    IF material_tracking_mode <> 'SERIALIZED' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_asset_material_serialized',
            MESSAGE = 'serialized asset requires a SERIALIZED material';
    END IF;

    SELECT location.active, location.can_hold_stock
    INTO location_active, location_can_hold_stock
    FROM public.locations_location AS location
    WHERE location.id = NEW.current_location_id
    FOR SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'serialized asset location does not exist';
    END IF;
    IF NOT location_active OR NOT location_can_hold_stock THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_asset_valid_location',
            MESSAGE = 'serialized asset requires an active stock-holding location';
    END IF;

    SELECT condition.active
    INTO condition_active
    FROM public.catalog_materialcondition AS condition
    WHERE condition.id = NEW.current_condition_id
    FOR SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'serialized asset condition does not exist';
    END IF;
    IF NOT condition_active THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_asset_active_condition',
            MESSAGE = 'serialized asset requires an active condition';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER inventory_serialized_asset_integrity_trg
BEFORE INSERT OR UPDATE OF material_id, current_location_id, current_condition_id, current_state
ON public.inventory_serializedasset
FOR EACH ROW
EXECUTE FUNCTION public.inventory_serialized_asset_integrity_guard();

CREATE OR REPLACE FUNCTION public.inventory_serialized_asset_identity_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM public.inventory_inventorytransactionline AS line
        WHERE line.serialized_asset_id = OLD.id
    ) THEN
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END IF;

    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            CONSTRAINT = 'inventory_asset_identity_history',
            MESSAGE = 'serialized asset identity with inventory history is immutable';
    END IF;

    IF NEW.material_id IS DISTINCT FROM OLD.material_id
       OR NEW.internal_asset_code IS DISTINCT FROM OLD.internal_asset_code
       OR NEW.serial_number IS DISTINCT FROM OLD.serial_number THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            CONSTRAINT = 'inventory_asset_identity_history',
            MESSAGE = 'serialized asset identity with inventory history is immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER inventory_serialized_asset_identity_update_trg
BEFORE UPDATE OF material_id, internal_asset_code, serial_number
ON public.inventory_serializedasset
FOR EACH ROW
EXECUTE FUNCTION public.inventory_serialized_asset_identity_guard();

CREATE TRIGGER inventory_serialized_asset_identity_delete_trg
BEFORE DELETE ON public.inventory_serializedasset
FOR EACH ROW
EXECUTE FUNCTION public.inventory_serialized_asset_identity_guard();

CREATE OR REPLACE FUNCTION public.inventory_material_tracking_mode_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.tracking_mode IS DISTINCT FROM OLD.tracking_mode
       AND (
           EXISTS (
               SELECT 1 FROM public.inventory_inventorytransactionline AS line
               WHERE line.material_id = OLD.id
           )
           OR EXISTS (
               SELECT 1 FROM public.inventory_stockbalance AS balance
               WHERE balance.material_id = OLD.id
           )
           OR EXISTS (
               SELECT 1 FROM public.inventory_serializedasset AS asset
               WHERE asset.material_id = OLD.id
           )
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_material_tracking_mode_history',
            MESSAGE = 'material tracking mode cannot change after inventory history';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.inventory_location_positive_stock_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF (
        (OLD.active AND NOT NEW.active)
        OR (OLD.can_hold_stock AND NOT NEW.can_hold_stock)
    ) AND (
        EXISTS (
            SELECT 1 FROM public.inventory_stockbalance AS balance
            WHERE balance.location_id = OLD.id AND balance.quantity > 0
        )
        OR EXISTS (
            SELECT 1 FROM public.inventory_serializedasset AS asset
            WHERE asset.current_location_id = OLD.id
              AND asset.current_state = 'IN_STOCK'
        )
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_location_positive_stock',
            MESSAGE = 'location with positive stock or serialized inventory cannot be deactivated or stop holding stock';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.inventory_condition_serialized_stock_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.active AND NOT NEW.active AND EXISTS (
        SELECT 1 FROM public.inventory_serializedasset AS asset
        WHERE asset.current_condition_id = OLD.id
          AND asset.current_state = 'IN_STOCK'
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_condition_serialized_stock',
            MESSAGE = 'condition used by current serialized inventory cannot be deactivated';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER inventory_condition_serialized_stock_trg
BEFORE UPDATE OF active ON public.catalog_materialcondition
FOR EACH ROW
EXECUTE FUNCTION public.inventory_condition_serialized_stock_guard();
"""


SERIALIZED_GUARD_SQL = _serialized_guard_sql()


RESTORE_PREVIOUS_AUXILIARY_GUARDS_SQL = r"""
DROP TRIGGER IF EXISTS inventory_condition_serialized_stock_trg
    ON public.catalog_materialcondition;
DROP FUNCTION IF EXISTS public.inventory_condition_serialized_stock_guard();

DROP TRIGGER IF EXISTS inventory_serialized_asset_identity_delete_trg
    ON public.inventory_serializedasset;
DROP TRIGGER IF EXISTS inventory_serialized_asset_identity_update_trg
    ON public.inventory_serializedasset;
DROP FUNCTION IF EXISTS public.inventory_serialized_asset_identity_guard();

DROP TRIGGER IF EXISTS inventory_serialized_asset_integrity_trg
    ON public.inventory_serializedasset;
DROP FUNCTION IF EXISTS public.inventory_serialized_asset_integrity_guard();

CREATE OR REPLACE FUNCTION public.inventory_material_tracking_mode_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.tracking_mode IS DISTINCT FROM OLD.tracking_mode
       AND (
           EXISTS (
               SELECT 1 FROM public.inventory_inventorytransactionline AS line
               WHERE line.material_id = OLD.id
           )
           OR EXISTS (
               SELECT 1 FROM public.inventory_stockbalance AS balance
               WHERE balance.material_id = OLD.id
           )
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_material_tracking_mode_history',
            MESSAGE = 'material tracking mode cannot change after inventory history';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.inventory_location_positive_stock_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF (
        (OLD.active AND NOT NEW.active)
        OR (OLD.can_hold_stock AND NOT NEW.can_hold_stock)
    ) AND EXISTS (
        SELECT 1 FROM public.inventory_stockbalance AS balance
        WHERE balance.location_id = OLD.id AND balance.quantity > 0
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_location_positive_stock',
            MESSAGE = 'location with positive stock cannot be deactivated or stop holding stock';
    END IF;
    RETURN NEW;
END;
$$;
"""


SERIALIZED_GUARD_REVERSE_SQL = r"""
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.inventory_serializedasset)
       OR EXISTS (
           SELECT 1 FROM public.inventory_inventorytransactionline
           WHERE serialized_asset_id IS NOT NULL
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'inventory_serialized_reverse_requires_no_data',
            MESSAGE = 'cannot reverse serialized inventory foundation while serialized data exists';
    END IF;
END;
$$;
""" + RESTORE_PREVIOUS_AUXILIARY_GUARDS_SQL + _previous_kernel.CONTROLLED_CORRECTION_GUARD_SQL


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_seed_material_conditions'),
        ('inventory', '0008_alter_inventorytransaction_options_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerializedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_asset_code', models.CharField(max_length=64)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('current_state', models.CharField(choices=[('IN_STOCK', 'Stokta')], default='IN_STOCK', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='inventorytransactionline',
            name='inventory_line_qty_positive',
        ),
        migrations.AlterField(
            model_name='inventorytransactionline',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytransactionline',
            name='unit',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_transaction_lines', to='catalog.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='serializedasset',
            name='current_condition',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='current_serialized_assets', to='catalog.materialcondition'),
        ),
        migrations.AddField(
            model_name='serializedasset',
            name='current_location',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='current_serialized_assets', to='locations.location'),
        ),
        migrations.AddField(
            model_name='serializedasset',
            name='material',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='serialized_assets', to='catalog.material'),
        ),
        migrations.AddField(
            model_name='inventorytransactionline',
            name='serialized_asset',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_transaction_lines', to='inventory.serializedasset'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransactionline',
            constraint=models.UniqueConstraint(condition=models.Q(('serialized_asset__isnull', False)), fields=('transaction', 'serialized_asset'), name='inventory_line_tx_asset_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransactionline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__isnull', True), ('quantity__gt', Decimal('0')), _connector='OR'), name='inventory_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransactionline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantity__isnull', False), ('serialized_asset__isnull', True), ('unit__isnull', False)), models.Q(('quantity__isnull', True), ('serialized_asset__isnull', False), ('unit__isnull', True)), _connector='OR'), name='inventory_line_tracking_shape'),
        ),
        migrations.AddIndex(
            model_name='serializedasset',
            index=models.Index(fields=['material'], name='inventory_asset_material_idx'),
        ),
        migrations.AddIndex(
            model_name='serializedasset',
            index=models.Index(fields=['current_location'], name='inventory_asset_location_idx'),
        ),
        migrations.AddConstraint(
            model_name='serializedasset',
            constraint=models.UniqueConstraint(fields=('internal_asset_code',), name='inventory_asset_internal_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serializedasset',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number__isnull', False)), fields=('material', 'serial_number'), name='inventory_asset_material_serial_uniq'),
        ),
        migrations.AddConstraint(
            model_name='serializedasset',
            constraint=models.CheckConstraint(condition=models.Q(('internal_asset_code__regex', '^\\s*$'), _negated=True), name='inventory_asset_internal_code_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='serializedasset',
            constraint=models.CheckConstraint(condition=models.Q(('serial_number__isnull', True), models.Q(('serial_number__regex', '^\\s*$'), _negated=True), _connector='OR'), name='inventory_asset_serial_nonblank_or_null'),
        ),
        migrations.AddConstraint(
            model_name='serializedasset',
            constraint=models.CheckConstraint(condition=models.Q(('current_state', 'IN_STOCK')), name='inventory_asset_state_in_stock'),
        ),
        migrations.RunSQL(
            sql=PRE_GUARD_ASSERTIONS_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=SERIALIZED_GUARD_SQL,
            reverse_sql=SERIALIZED_GUARD_REVERSE_SQL,
        ),
    ]
