"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

_TRUTHY = frozenset({'1', 'true', 'yes', 'on'})
_FALSY = frozenset({'0', 'false', 'no', 'off'})
_LOCAL_ALLOWED_HOSTS = ('localhost', '127.0.0.1', '[::1]')
_INSECURE_DEV_SECRET_KEY = 'insecure-local-bootstrap-only-not-for-production'


def env_bool(name: str, *, default: bool | None = None) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        if default is None:
            raise ImproperlyConfigured(f'{name} is required.')
        return default

    value = raw.strip().lower()
    if not value:
        if default is None:
            raise ImproperlyConfigured(f'{name} cannot be empty.')
        return default
    if value in _TRUTHY:
        return True
    if value in _FALSY:
        return False
    raise ImproperlyConfigured(
        f'{name} has invalid boolean value {raw!r}. '
        'Use true/false, 1/0, yes/no, or on/off.'
    )


def env_csv(name: str, *, default: tuple[str, ...] | list[str] = ()) -> list[str]:
    raw = os.environ.get(name)
    if raw is None:
        return list(default)
    return [item.strip() for item in raw.split(',') if item.strip()]


def resolve_secret_key(*, debug: bool) -> str:
    raw = os.environ.get('DJANGO_SECRET_KEY')
    if raw is not None and raw.strip():
        return raw
    if debug:
        return _INSECURE_DEV_SECRET_KEY
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false.'
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEBUG = env_bool('DJANGO_DEBUG', default=True)

# SECRET_KEY bootstrap: set DJANGO_SECRET_KEY in the environment for real use.
# The fallback is NOT a secret; development/bootstrap only; must not be used
# in production.
SECRET_KEY = resolve_secret_key(debug=DEBUG)

ALLOWED_HOSTS = env_csv('DJANGO_ALLOWED_HOSTS', default=_LOCAL_ALLOWED_HOSTS)

CSRF_TRUSTED_ORIGINS = env_csv('DJANGO_CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'core.apps.CoreConfig',
    'catalog.apps.CatalogConfig',
    'locations.apps.LocationsConfig',
    'inventory.apps.InventoryConfig',
    'corrections.apps.CorrectionsConfig',
    'counting.apps.CountingConfig',
    'imports.apps.ImportsConfig',
    'reports.apps.ReportsConfig',
    'audit.apps.AuditConfig',
]

# DEC-019: custom User must be configured before the first migrate.
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# PostgreSQL is the only supported V1 database backend. Set connection
# values via environment variables (see `.env.example`). Do not commit
# real passwords. An empty POSTGRES_PASSWORD default is configuration
# loading only; it is not a recommended PostgreSQL setup.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'tezcan_envanter'),
        'USER': os.environ.get('POSTGRES_USER', 'tezcan_envanter'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr-tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'var' / 'static'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'var' / 'media'


# Logging
# https://docs.djangoproject.com/en/5.2/topics/logging/

LOG_LEVEL = os.environ.get('DJANGO_LOG_LEVEL', 'INFO').upper()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
