# Generated by Django 5.2.17 on 2026-09-10 12:50

import django.db.models.deletion
import django.db.models.lookups
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=128)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('entity_type', models.CharField(max_length=128)),
                ('entity_id', models.UUIDField()),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['occurred_at'], name='audit_evt_occurred_at_idx'), models.Index(fields=['actor', 'occurred_at'], name='audit_evt_actor_occ_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_evt_entity_idx'), models.Index(fields=['event_type', 'occurred_at'], name='audit_evt_type_occ_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type__regex', '^\\s*$'), _negated=True), name='audit_evt_event_type_ne'), models.CheckConstraint(condition=models.Q(('entity_type__regex', '^\\s*$'), _negated=True), name='audit_evt_entity_type_ne'), models.CheckConstraint(condition=models.Q(('before_data__isnull', True), django.db.models.lookups.Exact(models.Func(models.F('before_data'), function='jsonb_typeof', output_field=models.CharField()), models.Value('object')), _connector='OR'), name='audit_evt_before_data_obj'), models.CheckConstraint(condition=models.Q(('after_data__isnull', True), django.db.models.lookups.Exact(models.Func(models.F('after_data'), function='jsonb_typeof', output_field=models.CharField()), models.Value('object')), _connector='OR'), name='audit_evt_after_data_obj'), models.CheckConstraint(condition=django.db.models.lookups.Exact(models.Func(models.F('metadata'), function='jsonb_typeof', output_field=models.CharField()), models.Value('object')), name='audit_evt_metadata_obj')],
            },
        ),
    ]
