# Generated by Django 5.2.17 on 2026-09-10 10:55

import django.core.validators
import django.db.models.deletion
import django.db.models.lookups
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('decimal_places', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code',), name='catalog_uom_code_uniq'), models.CheckConstraint(condition=models.Q(('code__regex', '^\\s*$'), _negated=True), name='catalog_uom_code_nonempty'), models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='catalog_uom_name_nonempty'), models.CheckConstraint(condition=models.Q(('decimal_places__isnull', True), models.Q(('decimal_places__gte', 0), ('decimal_places__lte', 3)), _connector='OR'), name='catalog_uom_dec_places_rng')],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_mode', models.CharField(choices=[('QUANTITY', 'Miktar'), ('SERIALIZED', 'Tekil')], max_length=10)),
                ('minimum_stock_value', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('technical_specs', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='materials', to='catalog.category')),
                ('unit', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='materials', to='catalog.unitofmeasure')),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='catalog_cat_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='catalog_cat_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='catalog_cat_name_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('code__isnull', True), models.Q(('code__regex', '^\\s*$'), _negated=True), _connector='OR'), name='catalog_cat_code_null_or_ne'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), models.Q(('parent_id', models.F('id')), _negated=True), _connector='OR'), name='catalog_cat_parent_not_self'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['material_code'], name='catalog_mat_code_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['name'], name='catalog_mat_name_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['category'], name='catalog_mat_category_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['unit'], name='catalog_mat_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['active'], name='catalog_mat_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('material_code__regex', '^\\s*$'), _negated=True), name='catalog_mat_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='catalog_mat_name_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('tracking_mode__in', ['QUANTITY', 'SERIALIZED'])), name='catalog_mat_track_mode_ok'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tracking_mode', 'QUANTITY'), _negated=True), ('unit__isnull', False), _connector='OR'), name='catalog_mat_qty_needs_unit'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_stock_value__isnull', True), ('minimum_stock_value__gte', Decimal('0')), _connector='OR'), name='catalog_mat_min_stock_nn'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(models.Func(models.F('technical_specs'), function='jsonb_typeof', output_field=models.CharField()), models.Value('object')), name='catalog_mat_tech_specs_obj'),
        ),
    ]
