# Generated by Django 5.2.17 on 2026-09-12 05:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code',), name='catalog_condition_code_uniq'), models.CheckConstraint(condition=models.Q(('code__regex', '^\\s*$'), _negated=True), name='catalog_condition_code_nonblank'), models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='catalog_condition_name_nonblank'), models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='catalog_condition_sort_nonnegative')],
            },
        ),
    ]
