# Generated by Django 5.2.17 on 2026-09-13 08:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


CORRECTION_REQUEST_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION public.correction_request_integrity_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    original_tx_type varchar(32);
    original_material_mode varchar(10);
    result_tx_type varchar(32);
BEGIN
    IF char_length(btrim(NEW.explanation)) < 10
       OR char_length(btrim(NEW.explanation)) > 2000
       OR NEW.explanation <> btrim(NEW.explanation) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'correction_explanation_length',
            MESSAGE = 'correction explanation must be trimmed and contain 10 to 2000 characters';
    END IF;

    SELECT tx.transaction_type, material.tracking_mode
    INTO original_tx_type, original_material_mode
    FROM public.inventory_inventorytransactionline AS line
    JOIN public.inventory_inventorytransaction AS tx
      ON tx.id = line.transaction_id
    JOIN public.catalog_material AS material
      ON material.id = line.material_id
    WHERE line.id = NEW.original_line_id
      AND line.transaction_id = NEW.original_transaction_id
      AND NEW.original_location_id IN (
            line.source_location_id,
            line.target_location_id
          )
    FOR KEY SHARE OF line, tx, material;

    IF NOT FOUND
       OR original_tx_type = 'CONTROLLED_CORRECTION'
       OR original_material_mode <> 'QUANTITY' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'correction_canonical_original_line',
            MESSAGE = 'correction request requires a quantity non-correction original line and bucket';
    END IF;

    IF NEW.effect_type = 'IDENTITY' THEN
        IF NOT EXISTS (
            SELECT 1
            FROM public.inventory_inventorytransactionline AS line
            WHERE line.id = NEW.original_line_id
              AND (
                    line.material_id <> NEW.corrected_material_id
                 OR line.condition_id <> NEW.corrected_condition_id
                 OR NEW.original_location_id <> NEW.corrected_location_id
              )
        ) THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'correction_identity_must_change',
                MESSAGE = 'identity correction must change material, location, or condition';
        END IF;
    END IF;

    IF NEW.requester_id IS NOT NULL
       AND NEW.requester_id = NEW.decided_by_id THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'correction_requester_not_decider',
            MESSAGE = 'correction requester cannot decide the same request';
    END IF;

    IF NEW.resulting_transaction_id IS NOT NULL THEN
        SELECT transaction_type
        INTO result_tx_type
        FROM public.inventory_inventorytransaction
        WHERE id = NEW.resulting_transaction_id
        FOR KEY SHARE;
        IF NOT FOUND OR result_tx_type <> 'CONTROLLED_CORRECTION' THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'correction_result_type',
                MESSAGE = 'approved correction result must be a CONTROLLED_CORRECTION transaction';
        END IF;
        IF EXISTS (
            SELECT 1
            FROM public.inventory_inventorytransactionline
            WHERE transaction_id = NEW.resulting_transaction_id
              AND corrected_line_id IS DISTINCT FROM NEW.original_line_id
        ) THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'correction_result_lineage',
                MESSAGE = 'correction result lines must reference the request original line';
        END IF;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        IF OLD.status <> 'PENDING' THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'correction_terminal_immutable',
                MESSAGE = 'terminal correction request cannot be changed';
        END IF;
        IF NEW.status NOT IN ('APPROVED', 'REJECTED')
           OR NEW.original_transaction_id IS DISTINCT FROM OLD.original_transaction_id
           OR NEW.original_line_id IS DISTINCT FROM OLD.original_line_id
           OR NEW.original_location_id IS DISTINCT FROM OLD.original_location_id
           OR NEW.requester_id IS DISTINCT FROM OLD.requester_id
           OR NEW.explanation IS DISTINCT FROM OLD.explanation
           OR NEW.effect_type IS DISTINCT FROM OLD.effect_type
           OR NEW.quantity_effect IS DISTINCT FROM OLD.quantity_effect
           OR NEW.corrected_material_id IS DISTINCT FROM OLD.corrected_material_id
           OR NEW.corrected_location_id IS DISTINCT FROM OLD.corrected_location_id
           OR NEW.corrected_condition_id IS DISTINCT FROM OLD.corrected_condition_id
           OR NEW.requested_at IS DISTINCT FROM OLD.requested_at THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'correction_request_immutable_fields',
                MESSAGE = 'submitted correction request fields are immutable';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER correction_request_integrity_trg
BEFORE INSERT OR UPDATE ON public.corrections_correctionrequest
FOR EACH ROW
EXECUTE FUNCTION public.correction_request_integrity_guard();

CREATE OR REPLACE FUNCTION public.correction_request_delete_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION USING
        ERRCODE = '23514',
        CONSTRAINT = 'correction_request_no_delete',
        MESSAGE = 'correction request rows cannot be deleted';
END;
$$;

CREATE TRIGGER correction_request_delete_trg
BEFORE DELETE ON public.corrections_correctionrequest
FOR EACH ROW
EXECUTE FUNCTION public.correction_request_delete_guard();
"""


CORRECTION_REQUEST_GUARD_REVERSE_SQL = r"""
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.corrections_correctionrequest) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'correction_request_reverse_requires_no_data',
            MESSAGE = 'cannot reverse correction workflow while correction request data exists';
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS correction_request_delete_trg
ON public.corrections_correctionrequest;
DROP FUNCTION IF EXISTS public.correction_request_delete_guard();
DROP TRIGGER IF EXISTS correction_request_integrity_trg
ON public.corrections_correctionrequest;
DROP FUNCTION IF EXISTS public.correction_request_integrity_guard();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_seed_material_conditions'),
        ('inventory', '0008_alter_inventorytransaction_options_and_more'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('explanation', models.TextField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(2000)])),
                ('effect_type', models.CharField(choices=[('QUANTITY', 'Miktar düzeltmesi'), ('IDENTITY', 'Kimlik düzeltmesi')], max_length=16)),
                ('quantity_effect', models.DecimalField(decimal_places=3, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corrected_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='correction_requests_as_corrected_condition', to='catalog.materialcondition')),
                ('corrected_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='correction_requests_as_corrected_location', to='locations.location')),
                ('corrected_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='correction_requests_as_corrected_material', to='catalog.material')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='decided_corrections', to=settings.AUTH_USER_MODEL)),
                ('original_line', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='correction_requests', to='inventory.inventorytransactionline')),
                ('original_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='correction_requests_as_original_bucket', to='locations.location')),
                ('original_transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='correction_requests', to='inventory.inventorytransaction')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requested_corrections', to=settings.AUTH_USER_MODEL)),
                ('resulting_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='resulting_correction_request', to='inventory.inventorytransaction')),
            ],
            options={
                'default_permissions': ('add', 'view'),
                'permissions': [('decide_correctionrequest', 'Can approve or reject correction request')],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='correction_status_req_idx'), models.Index(fields=['requester', 'requested_at'], name='correction_requester_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('original_transaction',), name='correction_one_pending_per_tx'), models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED', 'REJECTED'])), name='correction_status_supported'), models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('resulting_transaction__isnull', True), ('status', 'PENDING')), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('resulting_transaction__isnull', False), ('status', 'APPROVED')), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('resulting_transaction__isnull', True), ('status', 'REJECTED')), _connector='OR'), name='correction_decision_state_complete'), models.CheckConstraint(condition=models.Q(models.Q(('corrected_condition__isnull', True), ('corrected_location__isnull', True), ('corrected_material__isnull', True), ('effect_type', 'QUANTITY'), models.Q(('quantity_effect', Decimal('0')), _negated=True)), models.Q(('corrected_condition__isnull', False), ('corrected_location__isnull', False), ('corrected_material__isnull', False), ('effect_type', 'IDENTITY'), ('quantity_effect__gt', Decimal('0'))), _connector='OR'), name='correction_effect_shape')],
            },
        ),
        migrations.RunSQL(
            sql=CORRECTION_REQUEST_GUARD_SQL,
            reverse_sql=CORRECTION_REQUEST_GUARD_REVERSE_SQL,
        ),
    ]
