# Generated by Django 5.2.17 on 2026-09-16 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


CORRECTION_EVIDENCE_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION public.correction_evidence_immutability_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION USING
        ERRCODE = '23514',
        CONSTRAINT = 'correction_evidence_immutable',
        MESSAGE = 'correction evidence rows cannot be updated or deleted';
END;
$$;

CREATE TRIGGER correction_evidence_immutability_trg
BEFORE UPDATE OR DELETE ON public.corrections_correctionevidence
FOR EACH ROW
EXECUTE FUNCTION public.correction_evidence_immutability_guard();
"""

CORRECTION_EVIDENCE_GUARD_REVERSE_SQL = r"""
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.corrections_correctionevidence) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'correction_evidence_reverse_requires_no_data',
            MESSAGE = 'cannot reverse correction evidence while evidence metadata exists';
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS correction_evidence_immutability_trg
ON public.corrections_correctionevidence;
DROP FUNCTION IF EXISTS public.correction_evidence_immutability_guard();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correction_request', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evidence', to='corrections.correctionrequest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='uploaded_correction_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'default_permissions': (),
                'indexes': [models.Index(fields=['correction_request', 'created_at'], name='correction_evidence_req_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='correction_evidence_size_positive'), models.CheckConstraint(condition=models.Q(('content_type__in', ['image/jpeg', 'image/png', 'image/webp'])), name='correction_evidence_content_type_supported'), models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='correction_evidence_sha256_hex'), models.CheckConstraint(condition=models.Q(('storage_key__startswith', 'corrections/evidence/'), models.Q(('storage_key__contains', '..'), _negated=True), models.Q(('storage_key__contains', '\\'), _negated=True)), name='correction_evidence_storage_key_safe')],
            },
        ),
        migrations.RunSQL(
            sql=CORRECTION_EVIDENCE_GUARD_SQL,
            reverse_sql=CORRECTION_EVIDENCE_GUARD_REVERSE_SQL,
        ),
    ]
