# Generated by Django 5.2.17 on 2026-09-11 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('can_hold_stock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='locations.location')),
            ],
            options={
                'indexes': [models.Index(fields=['parent'], name='locations_loc_parent_idx'), models.Index(fields=['name'], name='locations_loc_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='locations_location_code_uniq'), models.CheckConstraint(condition=models.Q(('code__regex', '^\\s*$'), _negated=True), name='locations_location_code_nonblank'), models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='locations_location_name_nonblank'), models.CheckConstraint(condition=models.Q(('parent__isnull', True), models.Q(('parent_id', models.F('id')), _negated=True), _connector='OR'), name='locations_location_parent_not_self')],
            },
        ),
    ]
