# Generated by Django 5.2.17 on 2026-09-24 07:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


RECEIPT_LINK_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION public.procurement_receipt_link_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    line_material uuid;
    tx_type text;
    receipt_material uuid;
    receipt_qty numeric;
    receipt_asset uuid;
    line_count integer;
BEGIN
    SELECT material_id INTO line_material
    FROM procurement_purchaserequestline
    WHERE id = NEW.line_id;

    IF line_material IS NULL THEN
        RAISE EXCEPTION 'Talep kalemi malzemeye bağlı değil.';
    END IF;

    SELECT transaction_type INTO tx_type
    FROM inventory_inventorytransaction
    WHERE id = NEW.inventory_transaction_id;

    IF tx_type IS DISTINCT FROM 'RECEIPT' THEN
        RAISE EXCEPTION 'Yalnız stok girişi talep karşılamasına bağlanabilir.';
    END IF;

    SELECT COUNT(*) INTO line_count
    FROM inventory_inventorytransactionline
    WHERE transaction_id = NEW.inventory_transaction_id;

    IF line_count <> 1 THEN
        RAISE EXCEPTION 'Talep bağlantısı tek satırlı stok girişi gerektirir.';
    END IF;

    SELECT material_id, quantity, serialized_asset_id
    INTO receipt_material, receipt_qty, receipt_asset
    FROM inventory_inventorytransactionline
    WHERE transaction_id = NEW.inventory_transaction_id;

    IF receipt_material IS DISTINCT FROM line_material THEN
        RAISE EXCEPTION 'Stok girişi malzemesi talep kalemiyle uyuşmuyor.';
    END IF;

    IF receipt_asset IS NOT NULL THEN
        IF NEW.fulfilled_quantity <> 1 THEN
            RAISE EXCEPTION 'Tekil stok girişi tam bir varlık olarak sayılır.';
        END IF;
    ELSE
        IF receipt_qty IS NULL OR NEW.fulfilled_quantity <> receipt_qty THEN
            RAISE EXCEPTION 'Karşılanan miktar stok girişi miktarıyla aynı olmalıdır.';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER procurement_receipt_link_guard
BEFORE INSERT OR UPDATE ON procurement_purchaserequestreceipt
FOR EACH ROW
EXECUTE FUNCTION public.procurement_receipt_link_guard();

CREATE OR REPLACE FUNCTION public.procurement_receipt_link_delete_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Talep karşılama bağlantısı silinemez.';
END;
$$;

CREATE TRIGGER procurement_receipt_link_delete_guard
BEFORE DELETE ON procurement_purchaserequestreceipt
FOR EACH ROW
EXECUTE FUNCTION public.procurement_receipt_link_delete_guard();
"""

RECEIPT_LINK_GUARD_REVERSE_SQL = """
DROP TRIGGER IF EXISTS procurement_receipt_link_delete_guard
ON procurement_purchaserequestreceipt;
DROP FUNCTION IF EXISTS public.procurement_receipt_link_delete_guard();
DROP TRIGGER IF EXISTS procurement_receipt_link_guard
ON procurement_purchaserequestreceipt;
DROP FUNCTION IF EXISTS public.procurement_receipt_link_guard();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_material_generated_code_and_search_keywords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_no', models.CharField(max_length=64)),
                ('request_date', models.DateField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequestLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_description', models.TextField()),
                ('unit_code_snapshot', models.CharField(max_length=64)),
                ('unit_name_snapshot', models.CharField(max_length=255)),
                ('requested_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_arrival_date', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_request_lines', to='catalog.material')),
                ('purchase_request', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='lines', to='procurement.purchaserequest')),
                ('unit', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_request_lines', to='catalog.unitofmeasure')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequestReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fulfilled_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_request_receipts_created', to=settings.AUTH_USER_MODEL)),
                ('inventory_transaction_id', models.UUIDField()),
                ('line', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='receipts', to='procurement.purchaserequestline')),
            ],
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['request_date'], name='proc_req_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.UniqueConstraint(fields=('request_no',), name='proc_req_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(('request_no__regex', '^\\s*$'), _negated=True), name='proc_req_no_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(('approval_date__isnull', True), ('approval_date__gte', models.F('request_date')), _connector='OR'), name='proc_req_approval_ok'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestline',
            index=models.Index(fields=['purchase_request'], name='proc_line_req_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestline',
            index=models.Index(fields=['material'], name='proc_line_mat_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.CheckConstraint(condition=models.Q(('requested_description__regex', '^\\s*$'), _negated=True), name='proc_line_desc_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity__gt', Decimal('0'))), name='proc_line_qty_pos'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_code_snapshot__regex', '^\\s*$'), _negated=True), name='proc_line_unit_code_ne'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.CheckConstraint(condition=models.Q(('lead_time_days__isnull', True), ('lead_time_days__gte', 0), _connector='OR'), name='proc_line_lead_nn'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('currency_code__isnull', True), ('unit_price__isnull', True)), models.Q(('unit_price__gte', Decimal('0')), ('unit_price__isnull', False), ('currency_code__regex', '^[A-Z]{3}$')), _connector='OR'), name='proc_line_price_ccy'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestreceipt',
            index=models.Index(fields=['line'], name='proc_rcpt_line_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestreceipt',
            constraint=models.UniqueConstraint(fields=('inventory_transaction_id',), name='proc_rcpt_tx_uniq'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('fulfilled_quantity__gt', Decimal('0'))), name='proc_rcpt_qty_pos'),
        ),
        migrations.RunSQL(
            sql=RECEIPT_LINK_GUARD_SQL,
            reverse_sql=RECEIPT_LINK_GUARD_REVERSE_SQL,
        ),
    ]
